import type { Claim } from '../schema';
import { MOVING_PRECAUTIONS } from './food';
import { claim } from './make';

const moving = { movement: 'general', cautionIds: MOVING_PRECAUTIONS } as const;

/**
 * Checks at home: how often to check glucose for each kind of diabetes
 * medicine, what to write down and when to call; measuring blood pressure and
 * what its numbers mean; and the waist. Where guidelines draw a line in
 * different places (NICE and ADA on blood pressure, RSSDI and ICMR-NIN on the
 * waist) each is named beside the other, never merged. No claim sets a number
 * of glucose checks or an insulin dose (board D32; codex-acceptance J06, J12).
 */
export const CHECK_CLAIMS: Claim[] = [
  // How often to check glucose
  claim('gl-plan',
    'How often to check your sugar at home depends on your diabetes medicines and your situation. No single number of checks suits everyone, so agree a plan with your care team.',
    [['ada-soc-2026-s7', 'Recommendations 7.10 and 7.11'], ['icmr-t2dm-2018', 'Section 5.2, self-monitoring of blood glucose (pp. 14–15)'], ['rssdi-esi-2020', 'Glycaemic monitoring: recommendations for self-monitoring of blood glucose'], ['niddk-managing', 'Devices to help manage diabetes']]),
  claim('gl-hba1c',
    'The main test of how your diabetes is going over time is HbA1c, a blood test done at a lab rather than at home. ADA suggests it at least twice a year, and about every 3 months if you are not at your goal or your treatment has just changed.',
    [['ada-soc-2026-s6', 'Recommendations 6.1 and 6.2'], ['rssdi-esi-2020', 'Glycaemic monitoring: recommended care'], ['niddk-managing', 'A is for the A1C blood glucose test']]),
  claim('gl-no-hypo-meds',
    'If you don’t take insulin, a sulfonylurea or a meglitinide — for example, you manage with food and activity, or with metformin — you often don’t need to check every day. Ask your care team whether some checks would help you.',
    [['nice-ng28', 'Recommendation 1.6.2'], ['ada-soc-2026-s7', 'Recommendation 7.13']],
    { appliesTo: ['noHypoMedicine'] }),
  claim('gl-no-hypo-guides',
    'Guidelines differ on checks without those medicines. NICE in the UK doesn’t routinely offer home checks unless there is a reason, such as having had lows; ADA says they can help for a while when your food, activity or medicines change; and RSSDI in India suggests a few checks spread across the week when your sugar is steady, some of them after meals.',
    [['nice-ng28', 'Recommendation 1.6.2'], ['ada-soc-2026-s7', 'Recommendation 7.13'], ['rssdi-esi-2020', 'Glycaemic monitoring: Table 19, recommended frequency and timing of self-monitoring']],
    { appliesTo: ['noHypoMedicine'] }),
  claim('gl-su',
    'If you take a sulfonylurea, such as gliclazide or glimepiride, or a meglitinide: these tablets can make your sugar drop too low. Check whenever you feel a low coming on, and before you drive or exercise, as your care team advises.',
    [['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?; How do I treat low blood glucose?'], ['nice-ng28', 'Recommendations 1.6.2 and 1.6.3'], ['icmr-t2dm-2018', 'Section 7.1.2, sulphonylureas (p. 29)']],
    { appliesTo: ['sulfonylurea'] }),
  claim('gl-basal',
    'If you take long-acting (basal) insulin only: your care team will usually want fasting checks, taken before you eat in the morning. How often is for them to set, so follow their plan.',
    [['ada-soc-2026-s7', 'Recommendation 7.11; discussion of people using basal insulin'], ['rssdi-esi-2020', 'Glycaemic monitoring: Table 22 (patients on basal insulin)'], ['icmr-t2dm-2018', 'Section 5.2, self-monitoring of blood glucose (pp. 14–15)']],
    { appliesTo: ['basalInsulin'] }),
  claim('gl-mealtime',
    'If you take mealtime insulin — several injections a day — or use a pump: ADA suggests checking before meals and snacks, at bedtime, before, during and after activity, and before you drive. Check too whenever you think your sugar is low or high, and again after treating a low until it is back in range. Your care team will tell you how many checks that means for you.',
    [['ada-soc-2026-s7', 'Recommendation 7.11']],
    { appliesTo: ['mealtimeInsulin'] }),
  claim('gl-cost',
    'If test strips cost too much to check as often as suggested, say so to your care team. Indian guidance (RSSDI) says a checking plan should fit your situation, including what it costs.',
    [['rssdi-esi-2020', 'Glycaemic monitoring: recommendations for self-monitoring of blood glucose']]),
  claim('gl-cgm',
    'If you use a sensor (CGM), keep a meter as well, and use it to double-check when a sensor reading doesn’t match how you feel or the sensor gives a warning.',
    [['ada-soc-2026-s7', 'Recommendation 7.10'], ['niddk-managing', 'Devices to help manage diabetes']]),
  claim('gl-symptoms',
    'Signs of a low include shaking, sweating, a fast heartbeat, hunger, dizziness, and feeling nervous, cross or confused. Check whenever you notice them, and treat a low the way your care team has shown you.',
    [['cdc-low-sugar', 'Symptoms'], ['niddk-low-glucose', 'What are the symptoms of low blood glucose?; How do I treat low blood glucose?']],
    { appliesTo: ['hypoRisk'] }),

  // What to write down
  claim('gl-record',
    'Each time you check, write down the date, the time and the result, and when it was: fasting, before or after a meal, at bedtime, or around exercise.',
    [['niddk-managing', 'Devices to help manage diabetes'], ['ada-soc-2026-s7', 'Recommendation 7.11']]),
  claim('gl-meal-timing',
    'Before-meal and after-meal readings are judged against different targets, so it matters which one it was. For an after-meal check, also note when you started eating, because that target is timed from the start of the meal.',
    [['niddk-managing', 'Recommended targets for blood glucose levels']]),
  claim('gl-note-more',
    'Note anything that might explain a reading, such as what you ate, any activity, or being unwell.',
    [['niddk-managing', 'Devices to help manage diabetes'], ['nice-ng28', 'Recommendation 1.6.4']]),
  claim('gl-bring',
    'Take your readings to each visit, on paper or in an app, so your care team can see the pattern.',
    [['niddk-managing', 'Devices to help manage diabetes'], ['nice-ng28', 'Recommendation 1.6.5']]),
  claim('gl-strips',
    'Use test strips that are in date and stored as the pack says, bought from a pharmacy or licensed seller. Old or second-hand strips can give wrong readings.',
    [['ada-soc-2026-s7', 'Recommendation 7.12; discussion of strips from unlicensed sellers']]),

  // When to call
  claim('gl-tell-range',
    'Tell your care team if your readings are often above or below the range they have set for you.',
    [['niddk-managing', 'Recommended targets for blood glucose levels']],
    { caution: true }),
  claim('gl-tell-lows',
    'Tell your care team about every low, even one you treated yourself: ADA asks care teams to go over lows at every visit with anyone at risk of them.',
    [['ada-soc-2026-s6', 'Recommendation 6.10']],
    { appliesTo: ['hypoRisk'], caution: true }),
  claim('gl-ill',
    'Being ill can push your sugar up. When you are unwell, ask your care team whether to check more often and what to do about your medicines.',
    [['nice-ng28', 'Recommendation 1.6.4'], ['icmr-t2dm-2018', 'Section 5.2, self-monitoring of blood glucose (pp. 14–15)'], ['niddk-managing', 'What special situations should I plan for?']],
    { caution: true }),
  claim('gl-no-change',
    'Changes to your insulin are for your care team to make with you. This app never suggests a dose.',
    [['niddk-low-glucose', 'How can I prevent low blood glucose if I have diabetes?'], ['niddk-managing', 'What types of medicines should I take?']],
    { appliesTo: ['basalInsulin', 'mealtimeInsulin'], caution: true, policy: true }),
  claim('gl-severe-low',
    'If someone with diabetes is too confused to treat a low, passes out or has a fit, get emergency help straight away: a low like this can’t be treated by the person on their own. If a doctor has prescribed glucagon, the people close to you can learn when and how to give it.',
    [['niddk-low-glucose', 'What if I have severe low blood glucose and can’t treat myself?'], ['cdc-low-sugar', 'Severe low blood sugar'], ['ada-soc-2026-s6', 'Recommendation 6.16']],
    { appliesTo: ['hypoRisk'], caution: true, urgency: 'emergency' }),
  claim('gl-very-high',
    'Very high sugar can lead to confusion or fainting. If that happens, get emergency help straight away.',
    [['niddk-managing', 'High blood glucose']],
    { appliesTo: ['diabetes'], caution: true, urgency: 'emergency' }),
  claim('gl-serious-low',
    'After a serious low — under 54 mg/dL (3.0 mmol/L), or one where you needed someone’s help — contact your care team today: this app treats it as urgent. ADA says a low like this should lead to a review of your treatment plan.',
    [['cdc-low-sugar', 'Severe low blood sugar'], ['ada-soc-2026-s6', 'Recommendation 6.19']],
    { appliesTo: ['hypoRisk'], caution: true, urgency: 'soon', policy: true }),

  // Measuring blood pressure at home
  claim('bpm-why',
    'Checking your blood pressure at home shows how it runs from day to day and whether treatment is working. ADA advises home checks for everyone with diabetes and high blood pressure, once they have been shown how.',
    [['ada-soc-2026-s10', 'Recommendation 10.2'], ['aha-home-bp', 'Who should monitor blood pressure at home?']],
    { appliesTo: ['hypertension'] }),
  claim('bpm-device',
    'Use a validated monitor — one tested for accuracy — with a cuff that goes around your upper arm, in the right size for your arm. Wrist and finger monitors are less reliable. If you’re not sure about yours, ask your doctor or pharmacist.',
    [['aha-home-bp', 'Choosing a home blood pressure monitor'], ['aha-bp-2019', 'Table 9: preferred devices and cuffs'], ['nice-ng136', 'Recommendations 1.1.3 and 1.1.4']]),
  claim('bpm-before',
    'For 30 minutes before you measure, don’t smoke, exercise or have tea, coffee or other drinks with caffeine, and empty your bladder first.',
    [['aha-home-bp', 'How to use a home blood pressure monitor'], ['aha-bp-2019', 'Table 5: preparing the patient; Table 9: preparation']]),
  claim('bpm-sit',
    'Sit on a chair with your back supported, both feet flat on the floor and your legs uncrossed. Rest quietly for 5 minutes first, and don’t talk or use your phone while you measure.',
    [['aha-bp-2019', 'Table 9: preparation and position'], ['aha-home-bp', 'How to use a home blood pressure monitor'], ['nice-ng136', 'Recommendation 1.1.4']]),
  claim('bpm-arm',
    'Put the cuff on your bare upper arm, not over a sleeve, and rest that arm on a table so the cuff is at the level of your heart.',
    [['aha-home-bp', 'How to use a home blood pressure monitor'], ['aha-bp-2019', 'Table 5: cuff position; Table 9: position'], ['nice-ng136', 'Recommendation 1.1.4']]),
  claim('bpm-two-readings',
    'Take two readings at least a minute apart and write both down. On the days you check, do this in the morning and again in the evening.',
    [['nice-ng136', 'Recommendation 1.2.7'], ['aha-bp-2019', 'Table 9: number of readings'], ['aha-home-bp', 'How to use a home blood pressure monitor']]),
  claim('bpm-week',
    'To confirm high blood pressure, NICE asks for readings like these over at least 4 days, ideally 7. It leaves out the first day and uses the average of the rest.',
    [['nice-ng136', 'Recommendation 1.2.7']]),
  claim('bpm-bring',
    'Take your monitor to a clinic visit so your doctor can check it gives the same results as theirs, and bring your readings to every appointment.',
    [['aha-home-bp', 'Choosing a home blood pressure monitor; How to use a home blood pressure monitor'], ['aha-bp-2019', 'Table 9: patient training']]),
  claim('bpm-meds',
    'Don’t stop or change your blood pressure medicine because of your home readings; talk to your doctor about them. Take your morning readings before your tablets, at your usual time.',
    [['aha-home-bp', 'Who should monitor blood pressure at home?'], ['aha-bp-2019', 'Table 9: number of readings']],
    { caution: true }),

  // What the numbers mean
  claim('bpn-nice',
    'NICE, which writes guidelines for the UK, confirms high blood pressure when clinic readings are 140/90 or higher and the average of home readings is 135/85 or higher. It treats home readings as about 5 lower than clinic ones, which is why its home line is lower.',
    [['nice-ng136', 'Recommendations 1.2.8 and 1.4.19']]),
  claim('bpn-nice-target',
    'Once you are treated, NICE’s usual goal under age 80 is a home average below 135/85, or below 140/90 in clinic. From 80 on, it is below 145/85 at home, or 150/90 in clinic.',
    [['nice-ng136', 'Recommendations 1.4.20, 1.4.21 and 1.4.22']]),
  claim('bpn-ada',
    'For people with diabetes, ADA counts 130/80 or higher, found on two or more occasions, as high blood pressure. Its usual goal on treatment is below 130/80, if that can be reached safely.',
    [['ada-soc-2026-s10', 'Recommendations 10.1 and 10.4']],
    { appliesTo: ['diabetes'] }),
  claim('bpn-which',
    'These numbers come from different guidelines and measure different things: NICE’s 135/85 is for an average of home readings, its 140/90 is for clinic readings, and ADA’s 130/80 is for people with diabetes. Your own goal is the one you agree with your doctor.',
    [['nice-ng136', 'Recommendation 1.2.8'], ['ada-soc-2026-s10', 'Recommendations 10.1, 10.3 and 10.4']]),
  claim('bpn-one-reading',
    'One high reading on its own doesn’t mean you have high blood pressure. It goes up and down through the day, so it is judged on the average of many readings.',
    [['aha-home-bp', 'If you get a high blood pressure reading'], ['aha-bp-2019', 'Table 9: patient training'], ['nice-ng136', 'Recommendations 1.2.7 and 1.2.8']]),
  claim('bpn-ask-goal',
    'At your next visit, ask your doctor which goal is yours, whether it is for home or clinic readings, and what to do if your readings stay above it.',
    [['ada-soc-2026-s10', 'Recommendation 10.3'], ['nice-ng136', 'Recommendation 1.4.19']]),
  claim('bp-severe-emergency',
    'If the top number is 180 or more, or the bottom number 120 or more, and you have chest pain, breathlessness, back pain, numbness or weakness, a change in your vision, trouble speaking or new confusion, get emergency help straight away. Don’t wait to see if it comes down.',
    [['aha-bp-911', 'Hypertensive emergency'], ['nice-ng136', 'Recommendation 1.5.2']],
    { caution: true, urgency: 'emergency' }),
  claim('bp-severe-recheck',
    'If the top number is 180 or more, or the bottom number 120 or more, but you feel well, sit quietly for 5 minutes and measure again. If it is still that high, contact your doctor today: this app treats it as urgent.',
    [['aha-bp-911', 'Severe hypertension'], ['aha-home-bp', 'If you get a high blood pressure reading'], ['nice-ng136', 'Recommendation 1.5.1']],
    { caution: true, urgency: 'soon', policy: true }),

  // Waist and BMI
  claim('waist-rssdi',
    'Indian diabetes guidance (RSSDI-ESI 2020) counts a waist of 90 cm or more in men, or 80 cm or more in women, as a sign of extra fat around the tummy, called abdominal obesity.',
    [['rssdi-esi-2020', 'Obesity and type 2 diabetes mellitus: recommended care']]),
  claim('waist-nin',
    'ICMR-NIN’s 2024 dietary guidelines link a waist of more than 90 cm in men, or more than 80 cm in women, with a higher risk of long-term diseases such as diabetes and heart disease.',
    [['nin-dgi-2024', 'Guideline 9, rationale (p. 62) and waist circumference (p. 64)']]),
  claim('waist-same-line',
    'The two use the same lines and differ only at exactly 90 cm or 80 cm: RSSDI includes that measurement, while ICMR-NIN starts just above it. So a man’s waist of exactly 90 cm meets RSSDI’s cut-off but not ICMR-NIN’s.',
    [['rssdi-esi-2020', 'Obesity and type 2 diabetes mellitus: recommended care'], ['nin-dgi-2024', 'Guideline 9, waist circumference (p. 64)']]),
  claim('waist-why',
    'Fat around the tummy and the organs inside it is thought to be more harmful than fat elsewhere. It is linked with type 2 diabetes, high blood pressure, heart disease and fatty liver.',
    [['nin-dgi-2024', 'Guideline 9, rationale (p. 62) and central or abdominal obesity (p. 63)']]),
  claim('bmi-indian',
    'BMI cut-offs are lower for Indians too, because Asians tend to carry more body fat at the same BMI. WHO’s general normal range goes up to 25, but ICMR-NIN recommends 18.5 to 23. RSSDI counts 23 to 24.9 as overweight and 25 or more as obesity; ICMR-NIN counts over 23 to 27.5 as overweight and above 27.5 as obesity.',
    [['nin-dgi-2024', 'Guideline 9, what is overweight and obesity (pp. 62–64)'], ['rssdi-esi-2020', 'Obesity and type 2 diabetes mellitus: recommended care; identification of obesity']]),
  claim('waist-measure',
    'To measure your waist, stand up straight with your arms relaxed and little or no clothing over your tummy. Put the tape halfway between your lowest rib and the top of your hip bone, keep it level and snug but not pressing in, and read it at the end of a normal breath out.',
    [['who-waist-2011', 'Section 2.5, summary and conclusions (p. 7); section 5.2, measurement protocol (pp. 20–21)']]),
  claim('waist-keep',
    'To keep your weight and waist in a healthy range, ICMR-NIN suggests vegetables at every meal, whole grains, dal and beans, avoiding sugar, processed foods, fruit juice and foods high in fat, salt or sugar, and being active regularly.',
    [['nin-dgi-2024', 'Guideline 9, how to maintain appropriate body weight and waist circumference (p. 64)']],
    moving),
  claim('waist-slow',
    'If you are trying to lose weight, go slowly: ICMR-NIN considers losing about half a kilo a week to be safe.',
    [['nin-dgi-2024', 'Guideline 9, how to maintain appropriate body weight and waist circumference (p. 64)']]),
  claim('waist-visits',
    'Ask your doctor to measure your waist and weight at your check-ups: RSSDI advises this at every visit for people with type 2 diabetes, judged on Indian cut-offs.',
    [['rssdi-esi-2020', 'Obesity and type 2 diabetes mellitus: identification of obesity']],
    { appliesTo: ['type2'] }),
];
