import type { Claim } from '../schema';
import { MOVING_PRECAUTIONS, WALKING_PRECAUTIONS } from './food';
import { claim } from './make';

/** Standing and walking prompts give way, with an open foot wound, to something done seated. */
const SEATED = { when: 'footWound', with: ['desk-seated-change'] } as const;
const walking = { movement: 'weightBearing', cautionIds: WALKING_PRECAUTIONS } as const;
const moving = { movement: 'general', cautionIds: MOVING_PRECAUTIONS } as const;

/**
 * Desk setup and sitting, water, sleep, movement with back pain, and daily
 * habits. Where the evidence is a single study it is named as one, with the
 * people it was done in.
 */
export const DAILY_CLAIMS: Claim[] = [
  // Posture: there is no single right one
  claim('desk-no-single-posture',
    'There is no single right posture to hold all day. Staying still in any position for long isn’t healthy, so change position often.',
    [['osha-positions', 'Changing position']]),
  claim('desk-postures',
    'Sitting upright, leaning back a little, sitting with your thighs sloping slightly down, and standing are all good working positions to move between.',
    [['osha-positions', 'The four reference postures']]),
  claim('desk-ways-to-change',
    'Small changes count: adjust your chair or backrest, stretch your hands, arms and back, stand up and walk for a few minutes, or do some tasks standing.',
    [['osha-positions', 'Changing position']],
    { ...walking, swap: SEATED }),
  claim('desk-seated-change',
    'While you sit, you can still change position often: adjust your chair or backrest, and stretch your hands, arms and back.',
    [['osha-positions', 'Changing position']],
    { appliesTo: ['footWound'], cautionIds: ['walk-foot-wound'] }),

  // Setting up the desk
  claim('desk-lumbar',
    'Use a backrest that supports the curve of your lower back. If your chair has none, a rolled-up towel or cushion behind your lower back helps for now.',
    [['osha-chairs', 'Backrest']]),
  claim('desk-feet',
    'Sit so your feet rest flat on the floor. If the chair has to stay high for the desk, use a footrest.',
    [['osha-chairs', 'Seat']]),
  claim('desk-arms',
    'Keep your shoulders relaxed and your elbows close to your body, with the keyboard just below elbow height.',
    [['osha-chairs', 'Armrests'], ['hse-dse-posture', 'Standard workstation setup']]),
  claim('desk-screen',
    'Put the screen straight in front of you, about an arm’s length away, with the top of the screen at or slightly below eye level.',
    [['osha-monitors', 'Viewing distance; Viewing angle'], ['hse-dse-posture', 'Standard workstation setup']]),
  claim('desk-centred',
    'Keep the screen and keyboard centred in front of you so you don’t sit twisted.',
    [['hse-dse-posture', 'Standard workstation setup']]),
  claim('desk-laptop',
    'For long spells on a laptop, use a separate keyboard and mouse so the screen can be raised on a stand.',
    [['hse-dse-posture', 'Good posture for laptop use']]),
  claim('desk-text-size',
    'If you find yourself leaning in to read, make the text bigger instead.',
    [['osha-monitors', 'Viewing distance']]),
  claim('desk-eyes',
    'Rest your eyes now and then by looking at something far away, and remember to blink.',
    [['osha-monitors', 'Viewing time']]),
  claim('desk-back-link',
    'Poor back support and awkward postures at a desk can lead to back pain and tiredness.',
    [['osha-chairs', 'Backrest']],
    { appliesTo: ['backPain'] }),
  claim('desk-report-early',
    'Get aches, tingling or numbness that build up at the computer checked early, before they become a bigger problem.',
    [['osha-work-process', 'Recognising signs and symptoms']],
    { caution: true }),

  // Getting up from sitting
  claim('sit-30',
    'For blood sugar, ADA advises breaking up long spells of sitting at least every 30 minutes.',
    [['ada-soc-2026-s5', 'Recommendation 5.34']],
    { appliesTo: ['diabetes', 'prediabetes'], ...walking, swap: SEATED }),
  claim('sit-dempsey',
    'In a small study of adults with type 2 diabetes, a 3-minute light walk every 30 minutes during a long day of sitting lowered blood sugar and insulin after meals, compared with sitting throughout.',
    [['dempsey-2016', 'Abstract: Research design and methods; Results']],
    { appliesTo: ['diabetes'] }),
  claim('sit-hourly',
    'Every hour at a computer, take about five minutes away from the screen: look away, stretch, stand up or walk.',
    [['osha-work-process', 'Micro breaks or rest pauses']],
    { ...walking, swap: SEATED }),
  claim('sit-short-often',
    'Short, frequent breaks work better than long, occasional ones: five to ten minutes each hour is better than twenty minutes every two hours.',
    [['hse-dse-breaks', 'How long and how often breaks should be']]),
  claim('sit-nin-tips',
    'At work, ICMR-NIN suggests standing up every half hour, walking for 5–10 minutes every few hours, and taking phone calls on your feet.',
    [['nin-dgi-2024', 'Guideline 10, tips for a busy schedule (p. 71)']],
    { ...walking, swap: { when: 'footWound', with: [] } }),
  claim('sit-any-movement',
    'Replacing sitting time with movement of any kind, even light, is good for health.',
    [['who-pa-2020', 'Table 4: sedentary behaviour, adults']],
    moving),

  // Water
  claim('water-amount',
    'ICMR-NIN suggests a healthy adult drinks about eight glasses, roughly 2 litres, a day, counting all drinks, not only plain water.',
    [['nin-dgi-2024', 'Guideline 14 (p. 89)']]),
  claim('water-more',
    'You need more in very hot weather and when you are doing hard work or exercise, because you lose water in sweat.',
    [['nin-dgi-2024', 'Guideline 14 (p. 89)']]),
  claim('water-hot-weather',
    'In hot weather, chaas (buttermilk), nimbu pani made without sugar and tender coconut water are good drinks; soft drinks are not. Count any salt you add to them in your day’s salt.',
    [['nin-dgi-2024', 'Guideline 14, points to register (p. 92)'], ['ada-soc-2026-s5', 'Recommendation 5.25'], ['who-sodium-2026', 'Recommendations for reducing sodium']],
    { cautionIds: ['water-coconut', 'water-plan-first'] }),
  claim('water-coconut',
    'If you have kidney or heart disease and tend to run high potassium, avoid tender coconut water.',
    [['nin-dgi-2024', 'Guideline 14 (p. 89)']],
    { appliesTo: ['kidney', 'heart'], caution: true }),
  claim('water-safe',
    'If you are not sure your water is free of germs, boil it. Boiling does not remove chemicals, though, such as pesticides, heavy metals, arsenic or too much fluoride: if you think your water has those, use bottled water or another safe source, and ask your local health department for advice.',
    [['nin-dgi-2024', 'Guideline 14, when is water considered safe? and how is water rendered safe? (p. 89); points to register (p. 92)'], ['cdc-water-emergency', 'Water with fuel or toxic chemicals in it']]),
  claim('water-kidney',
    'With kidney disease, you may need to limit how much you drink, because damaged kidneys can’t clear extra fluid.',
    [['niddk-ckd-eating', 'Liquids']],
    { appliesTo: ['kidney'], caution: true }),
  claim('hf-salt-fluid',
    'With heart failure, your care team may ask you to limit salt and fluids, to stop fluid building up in the body.',
    [['nhlbi-heart-failure', 'Heart-healthy lifestyle changes']],
    { appliesTo: ['heart'], caution: true }),
  claim('water-plan-first',
    'If your care team has given you a fluid limit, follow it rather than general advice about drinking more, including advice in this app.',
    [['niddk-ckd-eating', 'Liquids; Track your liquids'], ['nhlbi-heart-failure', 'Heart-healthy lifestyle changes']],
    { appliesTo: ['fluidCaution'], caution: true }),
  claim('fluid-ask-amount',
    'Ask your care team how much fluid is right for you each day.',
    [['niddk-ckd-eating', 'Liquids'], ['nhlbi-heart-failure', 'Heart-healthy lifestyle changes']]),
  claim('fluid-salt',
    'Keep to the salt limit your care team gives you; salt makes the body hold on to fluid.',
    [['niddk-ckd-eating', 'Sodium'], ['nhlbi-heart-failure', 'Heart-healthy lifestyle changes']]),
  claim('fluid-swelling',
    'Contact your care team promptly, as your care plan says, about new or worsening swelling in your face, arms, legs or tummy, weight going up, or breathing that is getting worse — don’t wait for a routine visit. Ask them how often to weigh yourself and which signs need emergency care.',
    [['nhlbi-heart-failure', 'Know when to seek help'], ['niddk-ckd-eating', 'Track your liquids']],
    { appliesTo: ['fluidCaution'], caution: true, urgency: 'soon' }),
  claim('emergency-heart',
    'Get emergency help straight away for chest pain, pressure or heaviness — with or without sweating, sickness or sudden dizziness — or for breathlessness at rest that is new or severe, even if you are not sure it is your heart. This app treats collapsing, or not coming round normally after a faint, as an emergency too.',
    [['nhlbi-heart-attack', 'What are the symptoms of a heart attack?; When to call 9-1-1']],
    { caution: true, urgency: 'emergency', policy: true }),
  claim('stroke-signs',
    'Sudden weakness or numbness — even in one hand, or in the face, an arm or a leg, especially on one side — or sudden trouble speaking, seeing or keeping your balance can be a stroke. Get emergency help straight away; signs that pass after a few minutes still need a health care team straight away.',
    [['cdc-stroke', 'What are the signs of stroke in men and women?; When to seek emergency help; What should I do to treat a transient ischemic attack?'], ['nice-ng127', 'Recommendation 1.7.1']],
    { caution: true, urgency: 'emergency' }),

  // Sleep
  claim('sleep-hours',
    'CDC recommends 7 or more hours of sleep a day for adults aged 18 to 60, 7 to 9 hours from 61 to 64, and 7 to 8 hours from 65 on.',
    [['cdc-sleep', 'Getting enough sleep']]),
  claim('sleep-quality',
    'Quality matters as well as hours: trouble falling asleep, waking often in the night, or feeling tired after enough sleep are signs of poor sleep.',
    [['cdc-sleep', 'Sleep quality']]),
  claim('sleep-same-times',
    'Go to bed and get up at the same times every day.',
    [['cdc-sleep', 'What to do']]),
  claim('sleep-room',
    'Keep your bedroom quiet, relaxing and cool.',
    [['cdc-sleep', 'What to do']]),
  claim('sleep-screens',
    'Switch off your phone, the TV and other screens at least 30 minutes before bed.',
    [['cdc-sleep', 'What to do']]),
  claim('sleep-food-caffeine',
    'Avoid a heavy meal or alcohol close to bedtime, and tea, coffee or other caffeine in the afternoon and evening.',
    [['cdc-sleep', 'What to do']]),
  claim('sleep-active',
    'Regular exercise and a healthy diet help you sleep.',
    [['cdc-sleep', 'What to do']]),
  claim('sleep-ada-routine',
    'ADA advises people with diabetes to keep regular habits that support sleep.',
    [['ada-soc-2026-s5', 'Recommendation 5.57']],
    { appliesTo: ['diabetes'] }),
  claim('sleep-ada-screen',
    'ADA asks care teams to check on sleep, including sleep disorders, in people with diabetes or prediabetes, so it is fine to raise it.',
    [['ada-soc-2026-s5', 'Recommendation 5.56']],
    { appliesTo: ['diabetes', 'prediabetes'] }),
  claim('sleep-see-doctor',
    'Talk to your doctor if you regularly have problems sleeping or notice signs of a sleep disorder.',
    [['cdc-sleep', 'Management']],
    { caution: true }),
  claim('apnoea-signs',
    'Loud, frequent snoring, breathing that stops and starts in your sleep, daytime sleepiness and waking often at night to pass urine can be signs of sleep apnoea.',
    [['nhlbi-sleep-apnea', 'Symptoms while asleep and during the day']]),
  claim('apnoea-ask-someone',
    'You may not notice these signs yourself, so ask someone who sleeps near you whether they hear loud snoring or pauses in your breathing.',
    [['nhlbi-sleep-apnea', 'Symptoms while asleep and during the day']]),
  claim('apnoea-tell-doctor',
    'Tell your doctor about these signs; you may need a sleep study to check.',
    [['nhlbi-sleep-apnea', 'Talk to your healthcare provider']],
    { caution: true }),

  // Back pain and sciatica
  claim('back-normal-activities',
    'With low back pain or sciatica, keep up your normal daily activities as far as you can.',
    [['nice-ng59', 'Recommendation 1.2.1']],
    { appliesTo: ['backPain'], ...moving }),
  claim('back-exercise',
    'A group exercise programme can help — exercise for strength and movement, aerobic exercise, mind–body exercise, or a mix — chosen to suit your needs and what you can do.',
    [['nice-ng59', 'Recommendation 1.2.2']],
    moving),
  claim('back-no-belts',
    'NICE advises against belts or corsets for low back pain.',
    [['nice-ng59', 'Recommendation 1.2.3']],
    { appliesTo: ['backPain'] }),
  claim('back-walkback',
    'In adults who had recently recovered from an episode of non-specific low back pain, a walking programme that built up gradually, with a physiotherapist’s support, nearly doubled the time until back pain next limited their activities: a median of 208 days compared with 112.',
    [['walkback-2024', 'Abstract: Methods and Findings']]),
  claim('back-walkback-limits',
    'That trial was in people between episodes, so it is not evidence that walking treats a flare of sciatica or back pain. The walkers also reported more problems affecting their legs and feet.',
    [['walkback-2024', 'Abstract: Methods and Findings']]),
  claim('back-ces',
    'Get emergency help straight away for new trouble passing urine or controlling your bladder or bowels, new problems with sexual function, or new numbness around your genitals or back passage. NICE advises immediate assessment for these signs when severe back pain spreads into the leg; this app treats them as an emergency even if the pain is mild.',
    [['nice-ng127', 'Recommendation 1.7.3']],
    { caution: true, urgency: 'emergency', policy: true }),
  claim('back-weakness',
    'Get medical help straight away if weakness in both legs, or both arms, keeps getting worse over days or weeks.',
    [['nice-ng127', 'Recommendation 1.7.2']],
    { caution: true, urgency: 'emergency' }),
  claim('back-both-legs',
    'With back pain, new numbness, tingling or weakness in both legs — or weakness in both legs or both arms that keeps getting worse — needs emergency help straight away. NICE advises immediate referral when weakness on both sides worsens within weeks, or when numbness on both sides comes with weakness or unsteadiness and worsens over hours to days; this app treats any new symptoms in both legs with back pain as an emergency, even without weakness.',
    [['nice-ng127', 'Recommendations 1.7.2 and 1.10.2'], ['niams-back-pain', 'Symptoms of Back Pain']],
    { caution: true, urgency: 'emergency', policy: true }),
  claim('back-weakness-fast',
    'Weakness in one leg that is getting worse over hours or days needs emergency help straight away: this app treats rapid worsening as an emergency. NICE advises referral for investigation when weakness of one limb worsens that quickly.',
    [['nice-ng127', 'Recommendation 1.7.4']],
    { caution: true, urgency: 'emergency', policy: true }),
  claim('back-leg-weakness',
    'New weakness in one leg — a foot that drops, drags or slaps, or walking that has become harder — needs a doctor’s check. This app treats it as urgent: stop exercising and get assessed today; if it is getting worse quickly, that is an emergency.',
    [['niams-back-pain', 'Symptoms of Back Pain'], ['nice-ng127', 'Recommendation 1.7.5']],
    { caution: true, urgency: 'soon', policy: true }),
  claim('back-fever',
    'Back pain with a fever, shivering or feeling generally unwell — even if you haven’t taken your temperature — or pain that is severe and sudden or getting worse quickly needs a doctor’s check. This app treats these as urgent: get seen today, and don’t exercise until then.',
    [['niams-back-pain', 'Symptoms of Back Pain'], ['nice-ng59', 'Recommendation 1.1.1']],
    { caution: true, urgency: 'soon', policy: true }),
  claim('back-see-doctor',
    'See a doctor if back pain follows a fall or injury, comes with weight loss you didn’t intend, or is severe and doesn’t ease with painkillers.',
    [['niams-back-pain', 'Symptoms of Back Pain']],
    { caution: true }),
  claim('back-changed',
    'Tell your doctor about back symptoms that are new or changing; they can point to another cause that needs checking.',
    [['nice-ng59', 'Recommendation 1.1.1']],
    { caution: true }),
  claim('back-not-controlled',
    'See your doctor if sciatica pain isn’t controlled by painkillers or is stopping you doing everyday things.',
    [['nice-ng127', 'Recommendation 1.10.12']],
    { appliesTo: ['sciatica', 'backPain'], caution: true }),

  // How sciatica gets better: likely, not promised (codex-acceptance J16)
  claim('sci-gets-better',
    'Most people with a new episode of back pain or sciatica get better. The pain often eases within a few weeks, though for some people it takes a few months.',
    [['koes-2007', 'Summary points; What is the prognosis?'], ['nice-ng59-context', 'Context']],
    { appliesTo: ['sciatica', 'backPain'] }),
  claim('sci-some-longer',
    'For some people it lasts longer: in studies, up to about 3 in 10 people with sciatica still had pain a year or more later.',
    [['koes-2007', 'Summary points; What is the prognosis?']]),
  claim('sci-comes-back',
    'Back pain that has settled can come back later; NICE notes that this often happens.',
    [['nice-ng59-context', 'Context']]),
  claim('sci-bed-rest',
    'Bed rest is no better for sciatica than staying active: studies that compared the two found little difference.',
    [['koes-2007', 'What is the efficacy of conservative treatments for sciatica?']]),
  claim('sci-scan',
    'Scans such as an MRI are not usually needed for back pain or sciatica. NICE advises against routine scans outside specialist care, and suggests one only when the result is likely to change your treatment.',
    [['nice-ng59', 'Recommendations 1.1.4 and 1.1.6']]),
  claim('sci-not-easing',
    'If bad sciatica hasn’t eased after about 6 to 8 weeks, see your doctor about other ways to treat it.',
    [['koes-2007', 'Summary points; What is the value of imaging?']],
    { appliesTo: ['sciatica'], caution: true }),

  // How much activity
  claim('act-who',
    'WHO advises adults, including people with long-term conditions where they are able, to build up to 150–300 minutes of moderate activity a week, plus muscle-strengthening on two or more days.',
    [['who-pa-2020', 'Table 4: adults aged 18–64']],
    moving),
  claim('act-nin',
    'ICMR-NIN puts this as 30 to 60 minutes of moderate activity on at least five days a week for adults up to 60, plus muscle-strengthening on at least two days.',
    [['nin-dgi-2024', 'Guideline 10 (p. 70)']],
    moving),
  claim('act-ada',
    'For most adults with diabetes, ADA advises at least 150 minutes of moderate activity a week over at least three days, with no more than two days in a row without activity, plus resistance exercise two or three times a week on non-consecutive days.',
    [['ada-soc-2026-s5', 'Recommendations 5.36 and 5.37']],
    { appliesTo: ['diabetes'], ...moving }),
  claim('act-start-small',
    'Some activity is better than none. Start small and build up gradually.',
    [['who-pa-2020', 'Text introducing Table 4']],
    moving),
  claim('act-talk-test',
    'Aim for a brisk pace: breathing faster and deeper, but still able to talk. That is moderate activity.',
    [['nin-dgi-2024', 'Guideline 10 (p. 70)']],
    moving),
  claim('act-check-first',
    'If you have diabetes, high blood pressure or heart disease, ICMR-NIN advises checking with your doctor before you take up a new exercise programme.',
    [['nin-dgi-2024', 'Guideline 10, general tips (p. 71)']],
    { appliesTo: ['diabetes', 'hypertension', 'heart'], caution: true }),

  // Steps
  claim('steps-ding',
    'In a 2025 review of studies that followed adults over time, about 7,000 steps a day was linked with a 47% lower risk of death from any cause and a 14% lower risk of type 2 diabetes, compared with 2,000 steps. These are averages across many studies, not a prediction for you or for your age.',
    [['ding-2025', 'Abstract: Findings']]),
  claim('steps-realistic',
    'The authors suggest 7,000 a day may be a more realistic target than 10,000 for some people. Studies like these show links, not proof that the steps caused the difference.',
    [['ding-2025', 'Abstract: Interpretation']],
    moving),
  claim('steps-more',
    'A 2023 review found a steady link in studies that followed adults over time: the more steps people took each day, the lower their risk of death from any cause. It shows an association, not a threshold you need to reach.',
    [['banach-2023', 'Abstract: Results and Conclusion']]),
  claim('steps-build',
    'WHO’s guidelines are written in minutes of activity, not steps. Start from what you do now and build up gradually.',
    [['who-pa-2020', 'Table 4 and the text introducing it']],
    moving),

  // Alcohol
  claim('alc-no-safe',
    'WHO says there is no amount of alcohol that is safe for health.',
    [['who-alcohol-2023', 'Headline statement']]),
  claim('alc-dont-start',
    'If you don’t drink, don’t start; ADA advises against starting, even in moderation.',
    [['ada-soc-2026-s5', 'Recommendation 5.18']],
    { appliesTo: ['diabetes', 'prediabetes'] }),
  claim('alc-nin',
    'ICMR-NIN advises avoiding alcoholic drinks.',
    [['nin-dgi-2024', 'Guideline 14, points to register (p. 92); Guideline 9, points to register (p. 68)']]),
  claim('alc-bp',
    'Cutting down or stopping alcohol is part of ADA’s advice for managing blood pressure.',
    [['ada-soc-2026-s10', 'Recommendation 10.5']],
    { appliesTo: ['hypertension', 'bpUnsure'] }),
  claim('alc-sglt2',
    'If you take an SGLT2 inhibitor, avoid heavy drinking: drinking too much alcohol is one of the things that can bring on ketoacidosis with these medicines.',
    [['label-empagliflozin', '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis'], ['label-dapagliflozin', '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis']],
    { appliesTo: ['sglt2i'], cautionIds: ['sglt2-dka-signs'] }),
  claim('alc-delayed-lows',
    'With insulin or a sulfonylurea or meglitinide, alcohol can cause low blood sugar hours later. If you drink, eat something with it, check your sugar more often afterwards as your care plan says, and know the signs of a low.',
    [['ada-soc-2026-s5', 'Recommendation 5.19'], ['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?']],
    { appliesTo: ['hypoRisk'], caution: true }),

  // Tobacco
  claim('tob-avoid',
    'ADA advises people with diabetes to avoid tobacco and vaping completely.',
    [['ada-soc-2026-s5', 'Recommendation 5.40']]),
  claim('tob-benefit',
    'Stopping smoking helps at any age, and it can add as much as 10 years to life.',
    [['cdc-quit-benefits', 'Health benefits of quitting smoking']]),
  claim('tob-chewed',
    'WHO says every form of tobacco is harmful — chewed and smokeless tobacco and bidis included — and that there is no safe level.',
    [['who-tobacco', 'Key facts; Overview']]),
  claim('tob-vape',
    'ADA’s advice covers vaping too: it advises people with diabetes to avoid e-cigarettes as well as tobacco.',
    [['ada-soc-2026-s5', 'Recommendation 5.40']]),
  claim('tob-help',
    'Counselling and stop-smoking medicines together are the recommended way to quit.',
    [['ada-soc-2026-s5', 'Recommendation 5.40']]),
  claim('tob-tell-doctor',
    'ADA asks care teams to ask about tobacco and vaping routinely, so it is a normal thing to raise.',
    [['ada-soc-2026-s5', 'Recommendation 5.40']]),
  claim('tob-meds-doctor',
    'Stop-smoking medicines need a doctor’s advice; ask which would suit you.',
    [['ada-soc-2026-s5', 'Recommendation 5.40']],
    { caution: true }),
];
