import type { Claim } from '../schema';
import { claim } from './make';

/** What every walking or standing prompt carries, wherever it is shown (Codex content audit F02). */
export const WALKING_PRECAUTIONS = ['walk-carry-sugar', 'walk-feet', 'walk-foot-wound'];
/** What every other prompt to be active carries. */
export const MOVING_PRECAUTIONS = ['walk-carry-sugar', 'walk-foot-wound'];

/**
 * Food and diabetes, food and blood pressure, and the household measures the
 * meal templates may use. Our own words throughout: ICMR-NIN and ADA allow
 * citation, not reproduction (board D32).
 */
export const FOOD_CLAIMS: Claim[] = [
  // The plate. Neutral for everyone, the diabetes plate for people with
  // diabetes (surface scan S-14): Meal ideas is reached from Food & blood
  // pressure too, and its screens name these ids.
  claim('fd-plate-method',
    'A simple way to build a main meal is the plate method: about half the plate vegetables, a quarter protein foods such as dal, and a quarter grains such as rice or roti. ICMR-NIN’s plate for the day likewise fills about half with vegetables and fruit.',
    [['ada-diabetes-plate', 'Steps 1–3'], ['nin-dgi-2024', 'Guideline 1, My Plate for the Day (p. 6)']],
    { swap: { when: 'diabetes', with: ['fd-plate-diabetes'] } }),
  claim('fd-plate-diabetes',
    'Build each main meal on the diabetes plate: half non-starchy vegetables, a quarter protein foods and a quarter carbohydrate foods such as rice or roti.',
    [['ada-diabetes-plate', 'Steps 1–3']],
    { appliesTo: ['diabetes'] }),
  claim('fd-plate-size',
    'The plate method assumes a plate about 9 inches (23 cm) across. If your plate or thali is bigger, use a smaller plate, or fill only an area about 9 inches across.',
    [['ada-diabetes-plate', 'Introduction: a plate nine inches across']]),
  claim('fd-nonstarchy',
    'Non-starchy vegetables include bhindi (okra), baingan (brinjal), cabbage, cauliflower, palak and other leafy greens, cucumber, tomato, onion, mooli (radish) and green beans.',
    [['ada-diabetes-plate', 'Step 1: examples of non-starchy vegetables']]),
  claim('fd-gourds',
    'Everyday sabzi vegetables such as lauki (bottle gourd), tori (ridge gourd), karela (bitter gourd), tinda, gawar (cluster beans) and drumstick belong to the vegetable group, not with roots and tubers.',
    [['nin-dgi-2024', 'Annexure IV, Vegetables (p. 127)']]),
  claim('fd-starchy',
    'Count potato, sweet potato, corn and green peas in the carbohydrate quarter, not the vegetable half: they are starchy.',
    [['ada-diabetes-plate', 'Step 3: starchy vegetables']]),
  claim('fd-legumes-carbs',
    'Dal, chana and rajma are good protein foods, and they also carry a fair amount of carbohydrate.',
    [['ada-diabetes-plate', 'Step 2 (plant-based protein foods) and Step 3 (beans and legumes)']]),
  claim('fd-combination',
    'For mixed dishes such as khichdi or pulao, think about what is in them — grain, dal, vegetables — and keep roughly to the plate’s proportions.',
    [['ada-diabetes-plate', 'What about combination foods?']]),
  claim('fd-grains-yes',
    'Rice, roti and other grains can stay on your plate; keep them to about a quarter of it.',
    [['ada-diabetes-plate', 'Step 3: limiting carbohydrate foods to a quarter of the plate']]),
  claim('fd-whole-grains',
    'Make at least half of your grains whole or minimally polished: whole-wheat roti, minimally polished rice, or millets such as jowar, bajra or ragi eaten whole. A refined product, such as a biscuit made with millet flour, isn’t a whole grain just because it contains millet.',
    [['nin-dgi-2024', 'Guideline 1, healthy eating habits (p. 1); My Plate for the Day (p. 6)']]),
  claim('fd-portion-refined',
    'Where a whole grain doesn’t suit the dish — white rice with sambar, say — keep the rice to about a quarter of the plate.',
    [['ada-diabetes-plate', 'Step 3: limiting carbohydrate foods to a quarter of the plate']]),
  claim('fd-fibre',
    'Choose carbohydrate foods that are high in fibre and lightly processed — vegetables, dal and other legumes, whole fruit and whole grains — over refined grains and sweets.',
    [['ada-soc-2026-s5', 'Recommendations 5.14 and 5.24']]),
  claim('fd-healthy-meal',
    'ICMR-NIN’s picture of a healthy meal: plenty of vegetables, with whole grains and dal or beans, plain curd, some fruit and a few nuts or seeds, cooked with little oil and salt and little or no added sugar.',
    [['nin-dgi-2024', 'Guideline 1, what is a healthy meal (p. 1)']]),
  claim('fd-veg-every-meal',
    'Include vegetables, green leafy ones among them, in every meal.',
    [['nin-dgi-2024', 'Guideline 1, healthy eating habits (p. 1); Guideline 6, points to register (p. 50)']]),
  claim('fd-veg-in-dishes',
    'Cook vegetables into dal, khichdi and upma, or stir them into raita, as well as serving them on the side.',
    [['nin-dgi-2024', 'Guideline 6, points to register (p. 50)']]),
  claim('fd-cereal-pulse',
    'Eat dal or another pulse with your rice, roti or millet; together they give better-quality protein.',
    [['nin-dgi-2024', 'Guideline 8, points to register (p. 61); Guideline 9 (p. 66)']]),
  claim('fd-veg-protein',
    'Vegetarians can get good-quality protein from dal, beans, peas, milk and curd.',
    [['nin-dgi-2024', 'Guideline 8, points to register (p. 61)']],
    { appliesTo: ['lowAnimalFood'], cautionIds: ['ckd-protein'] }),
  claim('fd-plant-protein',
    'ADA advises people with diabetes to eat more plant protein — dal, chana, rajma, nuts and seeds — as part of a varied diet, to help lower the risk of heart disease.',
    [['ada-soc-2026-s5', 'Recommendation 5.29']],
    { appliesTo: ['diabetes', 'prediabetes'], cautionIds: ['ckd-protein'] }),
  claim('ckd-protein',
    'With kidney disease, ask your dietitian or care team how much protein is right for you, as well as potassium. Some people need moderate amounts, too little is harmful as well, and dialysis can mean needing more. Choosing more plant protein can mean swapping it for some meat or dairy, not eating more protein overall.',
    [['niddk-ckd-eating', 'Protein; Choose the amount and types of protein your body needs; Potassium']],
    { appliesTo: ['kidney'], caution: true }),
  claim('fd-dal-potassium',
    'Beans and lentils are good sources of potassium.',
    [['nin-dgi-2024', 'Guideline 11 (p. 73)']],
    { cautionIds: ['bp-potassium-kidney'] }),
  claim('fd-variety',
    'Vary your dals, grains and vegetables; each kind brings different nutrients.',
    [['nin-dgi-2024', 'Guideline 1, include variety within food groups (p. 2)']]),

  // Drinks, sugar and processed food
  claim('fd-water-first',
    'Make water your usual drink, and swap sweetened drinks and juices — even fresh juice — for water or unsweetened drinks.',
    [['ada-soc-2026-s5', 'Recommendations 5.21 and 5.25'], ['nin-dgi-2024', 'Guideline 14, points to register (p. 92)']],
    { cautionIds: ['water-plan-first'] }),
  claim('fd-added-sugar',
    'Keep sugar and foods with added sugar — mithai, biscuits, cakes and sweetened drinks — to a minimum.',
    [['ada-soc-2026-s5', 'Recommendations 5.14 and 5.25'], ['nin-dgi-2024', 'Guideline 15, points to register (p. 99)']]),
  claim('fd-fruit-whole',
    'Whole fruit is a better choice than juice. Fruit counts as a carbohydrate food, so it belongs in the carbohydrate quarter.',
    [['ada-diabetes-plate', 'Step 3: fruits'], ['nin-dgi-2024', 'Guideline 14, points to register (p. 92)']]),
  claim('fd-processed',
    'Go easy on packaged and ultra-processed foods — biscuits, chips, namkeen, instant foods and sugary breakfast cereals.',
    [['ada-soc-2026-s5', 'Recommendations 5.14 and 5.15'], ['nin-dgi-2024', 'Guideline 15 (pp. 94 and 99)'], ['who-sodium-2026', 'How can you reduce your sodium intake?']]),

  // Cooking
  claim('fd-fermented',
    'Fermenting, as in idli, dosa and dhokla, and sprouting both make grains and pulses easier to digest and their nutrients easier to absorb.',
    [['nin-dgi-2024', 'Guideline 13 (p. 81); points to register (p. 88)']],
    { cautionIds: ['food-safety-sprouts'] }),
  claim('food-safety-sprouts',
    'Diabetes and kidney disease can weaken the body’s defences, making food poisoning more likely. CDC lists raw or undercooked sprouts among the riskier foods and cooked sprouts as the safer choice, so cook sprouts before you eat them, and wash fruit and vegetables you eat raw.',
    [['cdc-food-safety', 'Why it’s important; Safer food choices: vegetables and fruits']],
    { caution: true }),
  claim('fd-cooking',
    'Steam or pressure-cook rather than deep-fry, and don’t reuse oil that has already been heated.',
    [['nin-dgi-2024', 'Guideline 13, points to register (p. 88); Guideline 7, points to register (p. 56)']]),
  claim('fd-oil',
    'Use cooking oil sparingly, keep ghee and butter to small amounts, and avoid vanaspati.',
    [['nin-dgi-2024', 'Guideline 7, points to register (p. 56)'], ['ada-soc-2026-s5', 'Recommendation 5.31']]),

  // Meal timing and snacks
  claim('fd-two-three-meals',
    'As general advice for healthy people, ICMR-NIN suggests two or three meals a day, without snacking in between.',
    [['nin-dgi-2024', 'Guideline 1, healthy eating habits (p. 2)']],
    { cautionIds: ['fd-meds-timing'] }),
  claim('fd-meds-timing',
    'If you take insulin or a sulfonylurea or meglitinide, keep to the meal and snack times agreed with your care team. Skipping or delaying a meal, or fasting, can make your sugar drop too low, so don’t drop a planned snack or fast because of general advice like this.',
    [['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?'], ['ada-soc-2026-s5', 'Recommendation 5.28']],
    { appliesTo: ['hypoRisk'], caution: true }),
  claim('fd-healthy-snacks',
    'If you do have a snack, good ones are fruit or vegetable salad with a few nuts or seeds and curd on top, or roasted or boiled chana, lobia, other beans or peanuts.',
    [['nin-dgi-2024', 'Guideline 1, what can make a healthy snack (p. 1)']]),

  // Supplements
  claim('fd-supplements',
    'ADA does not recommend supplements of vitamins or minerals, such as magnesium or chromium, or of herbs and spices, such as cinnamon or aloe vera, for lowering blood sugar.',
    [['ada-soc-2026-s5', 'Recommendation 5.16']]),
  claim('fd-tell-supplements',
    'Tell your care team about any supplements or herbal remedies you take, so they can check them against your medicines.',
    [['ada-soc-2026-s5', 'Recommendation 5.16'], ['ods-b12', 'Does vitamin B12 interact with medications or other dietary supplements?']],
    { caution: true }),

  // Boundaries. Neutral for everyone; ADA's diabetes meal plan for people with
  // diabetes (S-14). Both carry the medicine-timing exceptions (F06).
  claim('fd-personal-plan',
    'How much you need — your own portions — depends on your body, your weight and how active you are, so any amounts here are examples to adapt, not amounts set for you.',
    [['nin-dgi-2024', 'Notes to Figures 9.1 and 9.2 (pp. 63 and 65)'], ['nhlbi-dash', 'Overview']],
    { caution: true, cautionIds: ['fd-meds-timing', 'fd-fixed-insulin'], swap: { when: 'diabetes', with: ['fd-personal-plan-diabetes'] } }),
  claim('fd-personal-plan-diabetes',
    'How much you eat — your own portions and targets — is individual. ADA recommends a personal meal plan, ideally made with a dietitian who knows diabetes.',
    [['ada-soc-2026-s5', 'Recommendations 5.10 and 5.13']],
    { appliesTo: ['diabetes'], caution: true, cautionIds: ['fd-meds-timing', 'fd-fixed-insulin'] }),
  claim('fd-fixed-insulin',
    'If you use fixed insulin doses, eating carbohydrate at similar times and in similar amounts each day helps steady your sugar and lowers the risk of lows. Your care team will guide your meal and snack times.',
    [['ada-soc-2026-s5', 'Recommendation 5.28']],
    { appliesTo: ['hypoRisk'], caution: true }),
  claim('sglt2-keto',
    'For people with diabetes taking an SGLT2 inhibitor, ADA discourages ketogenic (very low-carbohydrate) eating. These medicines’ labels name a ketogenic diet as one of the things that can bring on ketoacidosis, so talk to your care team before a big change in how you eat.',
    [['ada-soc-2026-s5', 'Recommendation 5.26'], ['label-empagliflozin', '17 Patient Counseling Information: ketoacidosis'], ['label-dapagliflozin', '17 Patient Counseling Information: ketoacidosis']],
    { appliesTo: ['sglt2i'], caution: true, cautionIds: ['sglt2-dka-signs'] }),
  claim('sglt2-plan',
    'If you take an SGLT2 inhibitor, eating much less than usual — as in a fast — being unwell, or drinking heavily can bring on ketoacidosis. Ask your care team what to do about fasting, illness and checking ketones.',
    [['ada-soc-2026-s5', 'Recommendation 5.26'], ['label-empagliflozin', '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis'], ['label-dapagliflozin', '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis']],
    { appliesTo: ['sglt2i'], caution: true, cautionIds: ['sglt2-dka-signs'] }),
  claim('sglt2-dka-signs',
    'Ketoacidosis can happen even when your blood sugar is normal. If you take an SGLT2 inhibitor and feel sick or vomit, or have tummy pain, unusual tiredness or laboured breathing, get medical help straight away.',
    [['label-empagliflozin', '17 Patient Counseling Information: ketoacidosis'], ['label-dapagliflozin', '17 Patient Counseling Information: ketoacidosis']],
    { appliesTo: ['sglt2i'], caution: true, urgency: 'emergency' }),

  // Fasting
  claim('fast-ada',
    'If you plan a religious fast, ADA advises that your care team assesses the risks with you and reviews your medicines and their timing well before it, to lower the chance of lows, dehydration, high sugar or ketoacidosis.',
    [['ada-soc-2026-s5', 'Recommendations 5.32 and 5.33']],
    { appliesTo: ['diabetes'] }),
  claim('fast-plan',
    'Talk to your care team well before any fast, religious or for a medical test, so they can review your medicines and how to check your sugar during it.',
    [['ada-soc-2026-s5', 'Recommendation 5.33'], ['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?']]),
  claim('fast-lows',
    'Fasting while you keep taking medicines that lower blood sugar can make it drop too low.',
    [['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?']],
    { appliesTo: ['hypoRisk'], caution: true }),

  // Walking after meals
  claim('walk-meals-study',
    'In a crossover study of 41 adults with type 2 diabetes, each followed two kinds of advice for two weeks at a time: walk for 10 minutes after each main meal, or walk 30 minutes once a day. With the after-meal walks, the total rise in blood sugar over the three hours after meals was about 12% smaller, and 22% smaller after the evening meal.',
    [['reynolds-2016', 'Abstract: Methods and Results']],
    { appliesTo: ['diabetes'] }),
  claim('walk-meals-limits',
    'These are averages across the group, over two-week periods: they show a short-term effect, not a change you can count on in your own readings.',
    [['reynolds-2016', 'Abstract: Methods (2-week periods; outcome over the 3 hours after a meal) and Results']]),
  claim('walk-meals-try',
    'Try a 10-minute walk after your main meals. Dinner is where the study saw the biggest effect.',
    [['reynolds-2016', 'Abstract: Methods and Results']],
    { movement: 'weightBearing', cautionIds: WALKING_PRECAUTIONS, swap: { when: 'footWound', with: ['walk-foot-wound'] } }),
  claim('walk-carry-sugar',
    'If you take insulin or a sulfonylurea or meglitinide, activity can lower your sugar while you move and for hours afterwards. Check it before, during and after activity as your care plan says, and carry a fast-acting source of sugar.',
    [['niddk-low-glucose', 'What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?'], ['acsm-2022', 'Table 4: carrying rapid-acting carbohydrate']],
    { appliesTo: ['hypoRisk'], caution: true }),
  claim('walk-feet',
    'With nerve damage in your feet, check your feet every day, wear well-fitting shoes and socks, and avoid long walks on rough ground.',
    [['acsm-2022', 'Table 5: peripheral neuropathy']],
    { appliesTo: ['neuropathy'], caution: true }),
  claim('walk-foot-wound',
    'With an open foot wound or active Charcot foot, this app does not offer movement that puts weight through the affected foot until your care team clears it. Ask which activity and offloading are safe for you.',
    [['acsm-2022', 'Table 5: peripheral neuropathy (non-weight-bearing exercise; no aquatic exercise with unhealed plantar ulcers)']],
    { appliesTo: ['footWound'], caution: true, policy: true }),

  // Salt on Meal ideas: for everyone, and for high blood pressure (S-14)
  claim('meal-salt',
    'Cook with little salt: WHO and ICMR-NIN advise adults to keep to under 5 g a day in all, about one level teaspoon.',
    [['who-sodium-2026', 'Recommendations for reducing sodium'], ['nin-dgi-2024', 'Guideline 11 (p. 74) and points to register (p. 76)']],
    { swap: { when: 'hypertension', with: ['meal-salt-bp'] } }),
  claim('meal-salt-bp',
    'With high blood pressure, cutting salt helps: keep to under 5 g a day in all, counting salt in cooking and in packaged food. Plenty of vegetables, fruit, whole grains and dal, as in the DASH eating plan, helps too.',
    [['nin-dgi-2024', 'Guideline 11, rationale (p. 73) and points to register (p. 76)'], ['who-sodium-2026', 'Overview; Recommendations for reducing sodium'], ['nhlbi-dash', 'Overview']],
    { appliesTo: ['hypertension'], cautionIds: ['bp-potassium-kidney'] }),

  // Salt and blood pressure
  claim('salt-limit',
    'Keep salt below 5 g a day — about one level teaspoon — counting salt in cooking, at the table and in packaged food.',
    [['who-sodium-2026', 'Recommendations for reducing sodium'], ['nin-dgi-2024', 'Guideline 11 (p. 74) and points to register (p. 76)']]),
  claim('salt-why',
    'Too much salt raises blood pressure, which increases the risk of heart disease and stroke.',
    [['nin-dgi-2024', 'Guideline 11, rationale (p. 73)'], ['who-sodium-2026', 'Overview']]),
  claim('salt-ada',
    'ADA also advises people with diabetes to limit sodium, mainly by eating fewer processed foods.',
    [['ada-soc-2026-s5', 'Recommendation 5.20; Sodium']],
    { appliesTo: ['diabetes', 'prediabetes'] }),
  claim('salt-hidden-indian',
    'Pickle (achar), papad, namkeen and chips are high in salt; keep them for occasional, small helpings.',
    [['nin-dgi-2024', 'Guideline 11 (p. 74); Guideline 15 (p. 94)']]),
  claim('salt-hidden-packaged',
    'Bread and bakery foods, ready-made sauces and ketchup, instant foods, processed meat and cheese also carry a lot of hidden salt.',
    [['who-sodium-2026', 'Overview: sources of sodium; How can you reduce your sodium intake?'], ['nin-dgi-2024', 'Guideline 11 (p. 74); Guideline 15 (p. 94)']]),
  claim('salt-baking-soda',
    'Don’t add baking soda to soften chana, rajma or vegetables; it adds sodium just as salt does.',
    [['nin-dgi-2024', 'Guideline 13, points to register (p. 88); Guideline 11 (p. 74)']]),
  claim('salt-rock-black',
    'Rock salt (sendha namak) and black salt (kala namak) contain about as much sodium as ordinary salt, so limit them in the same way.',
    [['nin-dgi-2024', 'Guideline 11 (p. 75)']]),
  claim('salt-flavour',
    'Season with herbs and spices — ginger, pepper, turmeric, jeera — in place of extra salt.',
    [['who-sodium-2026', 'How can you reduce your sodium intake?']]),
  claim('salt-table',
    'Cook with less salt and keep the salt container off the table.',
    [['who-sodium-2026', 'How can you reduce your sodium intake?']]),
  claim('salt-iodised',
    'Use iodised salt, just less of it.',
    [['nin-dgi-2024', 'Guideline 11, points to register (p. 76)'], ['who-sodium-2026', 'Recommendations for reducing sodium']]),
  claim('bp-potassium-foods',
    'Vegetables and fruit are good sources of potassium, which helps the body get rid of sodium and keeps blood pressure in check.',
    [['nin-dgi-2024', 'Guideline 11, points to register (p. 76)']],
    { cautionIds: ['bp-potassium-kidney'] }),
  claim('bp-potassium-kidney',
    'With kidney disease, potassium can build up in the blood. Ask your care team how much potassium is right for you before eating more potassium-rich foods.',
    [['niddk-ckd-eating', 'Potassium']],
    { appliesTo: ['kidney'], caution: true }),
  claim('bp-dash',
    'For people with diabetes whose blood pressure is above 120/80, ADA advises a DASH-style way of eating with less salt, along with limiting alcohol, being more active, not smoking and losing weight if needed.',
    [['ada-soc-2026-s10', 'Recommendation 10.5']],
    { appliesTo: ['hypertension', 'bpUnsure'] }),
  claim('bp-dash-what',
    'DASH-style eating means plenty of vegetables, fruit and whole grains, with low-fat dairy, fish, poultry, beans and nuts, and less saturated fat, sugary drinks, sweets and salt.',
    [['nhlbi-dash', 'Overview']]),
  claim('bp-own-targets',
    'Your blood pressure goal should be set with your care team; ADA advises agreeing it together, based on your health and risks.',
    [['ada-soc-2026-s10', 'Recommendation 10.3']],
    { caution: true }),
  claim('lsss-what',
    'Low-sodium salt substitutes have less sodium than ordinary salt, and many replace some of it with potassium chloride, so check the label to see what is in yours.',
    [['who-lsss-2025', 'Executive summary: background']]),
  claim('lsss-caution',
    'Ask your doctor before switching to one. WHO’s advice on salt substitutes excludes people with kidney problems, and the trials behind it left out people taking potassium-sparing medicines and, in some cases, people with diabetes.',
    [['who-lsss-2025', 'Executive summary: The evidence; Scope of the recommendation']],
    { appliesTo: ['kidney', 'diabetes', 'hypertension'], caution: true }),
  claim('lsss-kidney',
    'If you have kidney disease and your potassium runs high, use herbs and spices rather than salt substitutes, which can be high in potassium.',
    [['niddk-ckd-eating', 'Choose foods that help keep your potassium level in the goal range']],
    { appliesTo: ['kidney'], caution: true }),
  claim('bp-meds-potassium',
    'Some blood pressure medicines, including ACE inhibitors, ARBs and spironolactone, can raise potassium levels; your doctor checks this with blood tests.',
    [['ada-soc-2026-s10', 'Recommendation 10.11']],
    { appliesTo: ['hypertension'], caution: true }),

  // Household measures for the meal templates
  claim('meal-katori',
    'In its sample diets, ICMR-NIN counts one katori as 200 ml, its medium size.',
    [['nin-dgi-2024', 'Annexure I (pp. 111–112); notes to Figures 9.1 and 9.2 (pp. 63 and 65)']]),
  claim('meal-curd-glass',
    'ICMR-NIN’s sample day for an adult has curd with lunch and dinner: one to one and a half small steel glasses, about 100 to 150 ml.',
    [['nin-dgi-2024', 'Annexure II, suggested diet for sedentary adults (p. 120)']]),
  claim('meal-fruit-katori',
    'In the same sample day, a serving of fruit is half a medium katori.',
    [['nin-dgi-2024', 'Annexure II, suggested diet for sedentary adults (p. 120)']]),
];
