import type { Claim } from '../schema';
import { claim } from './make';

/**
 * Vitamin B12 and vitamin D. These cards explain food, sunlight and when to
 * ask about a test. Treatment is a clinician's decision: no claim here names
 * a dose, and the integrity test fails if one ever does.
 */
export const VITAMIN_CLAIMS: Claim[] = [
  // B12: food
  claim('b12-sources',
    'Vitamin B12 comes from animal foods: milk, curd, paneer and other dairy, eggs, fish, chicken and meat.',
    [['ods-b12', 'What foods provide vitamin B12?'], ['nin-dgi-2024', 'Guideline 2 (p. 13)']]),
  claim('b12-plants',
    'Plant foods — dal, vegetables, greens and grains — contain no B12 unless it has been added to them.',
    [['ods-b12', 'What foods provide vitamin B12?']]),
  claim('b12-variety',
    'You can get enough B12 by eating a variety of these foods.',
    [['ods-b12', 'What foods provide vitamin B12?']],
    { cautionIds: ['b12-absorb'], swap: { when: 'lowAnimalFood', with: ['b12-low-animal-route'] } }),
  claim('b12-low-animal-route',
    'If you eat little or no animal food, milk, curd, paneer and eggs give some B12 if you eat them, and foods with B12 added or a supplement can make up the rest; plant foods have none of their own. Ask your care team which suits you.',
    [['ods-b12', 'What foods provide vitamin B12?; Am I getting enough vitamin B12?'], ['nin-dgi-2024', 'Guideline 1, nutrients of concern for vegetarians (p. 2)']],
    { appliesTo: ['lowAnimalFood'], cautionIds: ['b12-absorb'] }),
  claim('b12-absorb',
    'Eating these foods may not be enough if your body has trouble absorbing B12, as can happen with long-term metformin, acid-reducing medicines, some stomach or bowel surgery, or coeliac disease. If you already know you are low, follow the treatment your doctor recommends; food alone may not put it right.',
    [['ods-b12', 'Am I getting enough vitamin B12?; Interactions, including metformin'], ['nice-ng239', 'Box 2: risk factors; Recommendations 1.5.3 to 1.5.6 and 1.5.11 to 1.5.14']],
    { caution: true }),
  claim('b12-vegetarian-hard',
    'For vegetarians, getting enough B12 is a challenge; milk has only a small amount.',
    [['nin-dgi-2024', 'Guideline 1, nutrients of concern for vegetarians (p. 2)']],
    { appliesTo: ['vegetarian', 'eggetarian'] }),
  claim('b12-low-animal-risk',
    'People who eat little or no animal food — including vegans and people who avoid meat for religious reasons — are more likely to run low on B12.',
    [['ods-b12', 'Am I getting enough vitamin B12?'], ['nice-ng239', 'Box 2: risk factors']],
    { appliesTo: ['lowAnimalFood'] }),
  claim('b12-label',
    'Some packaged foods have B12 added, so check the label; adding vitamins does not make a processed food healthy, though.',
    [['ods-b12', 'What foods provide vitamin B12?'], ['nin-dgi-2024', 'Guideline 15, points to register (p. 99)']]),

  // B12: medicines, symptoms and testing
  claim('b12-metformin',
    'Metformin can lower B12 over time. ADA advises considering a B12 check now and then for anyone on long-term metformin, especially with anaemia or nerve symptoms.',
    [['ada-soc-2026-s3', 'Recommendation 3.10'], ['ods-b12', 'Does vitamin B12 interact with medications or other dietary supplements?']],
    { appliesTo: ['metformin', 'metforminUnknown'] }),
  claim('b12-metformin-yearly',
    'In the discussion that goes with its B12 recommendation, ADA suggests a yearly B12 check after more than four years on metformin, or sooner for anyone with another risk, such as a vegan diet.',
    [['ada-soc-2026-s3', 'Discussion of recommendation 3.10']],
    { appliesTo: ['metformin', 'metforminUnknown'] }),
  claim('b12-ask-monitoring',
    'If you have taken metformin for a long time, ask your doctor whether, and how often, your B12 should be checked — even if you feel well.',
    [['ada-soc-2026-s3', 'Recommendation 3.10']],
    { appliesTo: ['metformin', 'metforminUnknown'] }),
  claim('b12-other-medicines',
    'Some other medicines are linked with low B12 too, including acid-reducing medicines (proton pump inhibitors such as omeprazole, and H2 blockers) and pregabalin.',
    [['nice-ng239', 'Box 2: risk factors'], ['ods-b12', 'Does vitamin B12 interact with medications or other dietary supplements?']]),
  claim('b12-symptoms',
    'Low B12 can cause tiredness, weakness, numbness or tingling in the hands and feet, balance problems, memory trouble and a sore tongue.',
    [['ods-b12', 'What happens if I don’t get enough vitamin B12?'], ['nice-ng239', 'Box 1: symptoms and signs']]),
  claim('b12-slow',
    'The body holds large stores of B12, so a shortage can take years to show.',
    [['ods-b12', 'What happens if I don’t get enough vitamin B12?']]),
  claim('b12-when-tested',
    'Doctors usually test B12 when someone has a symptom like these and a risk factor such as metformin or a diet low in animal foods.',
    [['nice-ng239', 'Recommendation 1.2.5; Box 1: symptoms and signs; Box 2: risk factors']]),
  claim('b12-ask-test',
    'If you have a symptom such as tingling or unusual tiredness and a risk such as metformin or a diet low in animal foods, ask your doctor whether a B12 test makes sense.',
    [['nice-ng239', 'Recommendation 1.2.5; Box 1: symptoms and signs; Box 2: risk factors'], ['ada-soc-2026-s3', 'Recommendation 3.10']]),
  claim('b12-doctor-decides',
    'Whether you need a B12 test, tablets or injections is for your doctor to decide. Tell them about any supplements you already take.',
    [['nice-ng239', 'Recommendation 1.2.5'], ['ods-b12', 'What kinds of vitamin B12 dietary supplements are available?; Does vitamin B12 interact with medications or other dietary supplements?']],
    { caution: true }),
  claim('b12-numbness-check',
    'New or worsening numbness, tingling or weakness needs a doctor’s assessment; don’t assume the cause.',
    [['nice-ng239', 'Box 1: symptoms and signs'], ['nice-ng127', 'Recommendations 1.7.2 and 1.7.3']],
    { caution: true }),

  // Vitamin D: sunlight
  claim('d-sun',
    'Your skin makes vitamin D when bare skin is out in sunlight.',
    [['ods-vitamin-d', 'Can I get vitamin D from the sun?'], ['nin-dgi-2024', 'Guideline 1 (p. 1)']]),
  claim('d-sun-varies',
    'How much it makes varies with season, time of day, clouds, smog, age and skin colour — darker skin makes less — and none is made through a window. That is why there is no reliable number of minutes in the sun that suits everyone.',
    [['ods-vitamin-d-hp', 'Sources of Vitamin D: Sun exposure'], ['ods-vitamin-d', 'Can I get vitamin D from the sun?']]),
  claim('d-get-outside',
    'Time outdoors with some skin uncovered is how the body makes vitamin D; sunlight through a window doesn’t count.',
    [['ods-vitamin-d', 'Can I get vitamin D from the sun?'], ['nin-dgi-2024', 'Guideline 1 (p. 1)']],
    { cautionIds: ['d-sun-skin'] }),
  claim('d-sun-skin',
    'Sunlight’s UV rays can also cause skin cancer, so it is wise to limit how long you spend in the sun.',
    [['ods-vitamin-d', 'Can I get vitamin D from the sun?'], ['ods-vitamin-d-hp', 'Sources of Vitamin D: Sun exposure']],
    { caution: true }),
  claim('d-indoors',
    'People who spend most of the day indoors, such as at a desk job, or who keep their skin covered, are less likely to get enough vitamin D from sunlight.',
    [['ods-vitamin-d-hp', 'Groups at risk: people with limited sun exposure'], ['ods-vitamin-d', 'Am I getting enough vitamin D?']]),

  // Vitamin D: food
  claim('d-foods',
    'Few foods have much vitamin D. Fatty fish such as salmon, mackerel and tuna are among the best food sources; egg yolks and cheese have a little, and some mushrooms more if they have been exposed to UV light.',
    [['ods-vitamin-d', 'What foods provide vitamin D?']]),
  claim('d-label',
    'Some foods have vitamin D added, so check the label.',
    [['ods-vitamin-d', 'What foods provide vitamin D?']]),
  claim('d-vegan',
    'Vitamin D deficiency is more common in people who follow a vegan diet or avoid milk because of an allergy or lactose intolerance. That is about groups of people; it doesn’t tell you your own level.',
    [['ods-vitamin-d-hp', 'Vitamin D Deficiency']],
    { appliesTo: ['vegan'] }),
  claim('d-at-risk',
    'People more likely to run low include older adults, people who rarely get sun on their skin, people with darker skin, and people with obesity or conditions that affect how fat is absorbed.',
    [['ods-vitamin-d', 'Am I getting enough vitamin D?']]),

  // Vitamin D: testing and supplements
  claim('d-no-routine-test',
    'For adults with no specific medical reason, the Endocrine Society advises against routine vitamin D blood tests.',
    [['endocrine-vitamin-d-2024', 'Recommendations 3, 5 and 7']]),
  claim('d-diabetes',
    'Vitamin D supplements are not a way to lower blood sugar: in trials they did not improve blood sugar or HbA1c, and ADA does not recommend vitamin supplements for that. Treating a deficiency, or a doctor’s choice to use vitamin D alongside lifestyle changes for someone with high-risk prediabetes, is a separate decision.',
    [['ods-vitamin-d', 'What are some effects of vitamin D on health? (Type 2 diabetes)'], ['ada-soc-2026-s5', 'Recommendation 5.16'], ['endocrine-vitamin-d-2024', 'Recommendation 10']],
    { appliesTo: ['diabetes'] }),
  claim('d-ask-test',
    'If you’re worried you are low, ask your doctor whether a test is needed for you.',
    [['endocrine-vitamin-d-2024', 'Recommendations 3, 5 and 7']]),
  claim('d-too-much',
    'Too much vitamin D is harmful, and that almost always comes from supplements, not from sunlight.',
    [['ods-vitamin-d', 'Can vitamin D be harmful?']],
    { caution: true }),
  claim('d-thiazide',
    'If you take a thiazide-type water pill for blood pressure, vitamin D supplements could push your calcium too high, so ask your doctor first.',
    [['ods-vitamin-d', 'Does vitamin D interact with medications or other dietary supplements?']],
    { appliesTo: ['diuretic'], caution: true }),
  claim('d-doctor-decides',
    'Whether you need a vitamin D test or supplement, and how much, is for your doctor to decide.',
    [['endocrine-vitamin-d-2024', 'Recommendations 3, 5 and 7'], ['ods-vitamin-d', 'Can vitamin D be harmful?']],
    { caution: true }),
];
