import { REVIEWED } from './claims';
import { ROUTES, type GuidanceCard } from './schema';

const card = (c: Omit<GuidanceCard, 'reviewedDate' | 'notes' | 'related'> & Partial<Pick<GuidanceCard, 'notes' | 'related'>>): GuidanceCard =>
  ({ notes: [], related: [], ...c, reviewedDate: REVIEWED });

const MEALS = { label: 'See meal ideas', to: ROUTES.meals } as const;
const WALK = { label: 'Start a walk', to: ROUTES.walk, hideWhen: 'footWound' } as const;
const STRETCH = { label: 'Start a gentle stretch', to: ROUTES.stretch } as const;
const ADD_GLUCOSE = { label: 'Add a glucose reading', to: ROUTES.addGlucose } as const;
const ADD_BP = { label: 'Add a blood pressure reading', to: ROUTES.addBloodPressure } as const;
const ADD_WAIST = { label: 'Add a waist measurement', to: ROUTES.addWaist } as const;

/** Help now for a low that can't be self-treated or a very high with confusion; then the same-day call after a serious low. */
const GLUCOSE_HELP = ['gl-severe-low', 'gl-very-high', 'gl-serious-low'];

/**
 * Back red flags, before any movement on every back card (Codex content audit
 * F04, re-check R01 and R02): emergencies first — bladder, bowel or saddle
 * changes, stroke, both legs, one leg getting worse fast — then what needs a
 * doctor the same day. Each matches a row of the safety contract.
 */
export const BACK_RED_FLAGS = ['back-ces', 'stroke-signs', 'back-both-legs', 'back-weakness-fast', 'back-leg-weakness', 'back-fever'];

/**
 * Every card is made only of claim ids: the answer, what you can do, and
 * when to check with a doctor. Titles, questions and search aliases are the
 * card's own; nothing a person reads as health guidance is.
 */
export const CARDS: GuidanceCard[] = [
  // Food & diabetes
  card({
    id: 'card-plate',
    topics: ['food-diabetes'],
    title: 'Building your plate',
    question: 'How should I fill my plate with diabetes?',
    aliases: ['thali', 'plate method', 'diabetes plate', 'portion', 'portions', 'how much to eat', 'diet plan', 'diabetic diet', 'sugar diet', 'meal plan', 'khana', 'biryani', 'pulao', 'khichdi', 'aloo', 'batata', 'potato', 'shakarkandi', 'sweet potato', 'makka', 'bhutta', 'corn',
      'matar', 'peas', 'थाली', 'आलू'],
    answer: ['fd-plate-method', 'fd-plate-size'],
    notes: ['fd-nonstarchy', 'fd-gourds', 'fd-healthy-meal'],
    actions: ['fd-veg-every-meal', 'fd-starchy', 'fd-combination', 'fd-veg-in-dishes'],
    cautions: ['fd-personal-plan', 'fd-fixed-insulin', 'sglt2-keto'],
    related: ['card-grains', 'card-dal', 'card-drinks', 'card-fasting'],
    action: MEALS,
    furtherReading: ['nin-dgi-booklet'],
  }),
  card({
    id: 'card-grains',
    topics: ['food-diabetes'],
    title: 'Rice, roti and millets',
    question: 'Can I still eat rice and roti?',
    aliases: [
      'chawal', 'bhat', 'rice', 'roti', 'chapati', 'chapathi', 'phulka', 'paratha', 'atta', 'millet', 'millets', 'jowar', 'bajra', 'ragi',
      'nachni', 'brown rice', 'carbs', 'carbohydrate', 'grains', 'whole grain', 'maida', 'refined flour', 'suji', 'sooji', 'rava', 'rawa',
      'dalia', 'daliya', 'oats', 'idli', 'dosa', 'chapatti', 'chappati', 'fulka', 'rotli', 'parantha', 'chaval', 'bhaat', 'basmati',
      'चावल', 'रोटी', 'आटा', 'चपाती',
    ],
    answer: ['fd-grains-yes', 'fd-whole-grains'],
    notes: ['fd-fermented'],
    actions: ['fd-portion-refined', 'fd-fibre', 'fd-cereal-pulse', 'fd-variety'],
    cautions: ['fd-personal-plan', 'sglt2-keto'],
    related: ['card-plate', 'card-dal'],
    action: MEALS,
  }),
  card({
    id: 'card-dal',
    topics: ['food-diabetes'],
    title: 'Dal, chana and rajma',
    question: 'Are dal and beans good for diabetes?',
    aliases: [
      'daal', 'dhal', 'dal', 'lentils', 'pulses', 'beans', 'chana', 'chole', 'chickpeas', 'rajma', 'kidney beans', 'moong', 'masoor', 'toor',
      'arhar', 'urad', 'lobia', 'sprouts', 'protein', 'sambar', 'besan', 'chana dal', 'moong dal', 'dhokla', 'chilla', 'channa', 'chhole', 'rajmah', 'tuvar', 'toovar', 'masur',
      'mung', 'sambhar', 'दाल', 'राजमा', 'छोले', 'चना',
    ],
    answer: ['fd-legumes-carbs', 'fd-plant-protein'],
    notes: ['fd-veg-protein', 'fd-dal-potassium'],
    actions: ['fd-cereal-pulse', 'fd-healthy-snacks', 'salt-baking-soda', 'fd-veg-in-dishes'],
    cautions: ['fd-personal-plan', 'bp-potassium-kidney'],
    related: ['card-plate', 'card-grains', 'card-b12-food'],
    action: MEALS,
  }),
  card({
    // Built only from claims already used by the meal swaps, so a search for
    // ghee, oil or a fried snack finds an answer, not nothing.
    id: 'card-oil-ghee',
    topics: ['food-diabetes', 'food-bp'],
    title: 'Ghee, oil and fried snacks',
    question: 'Can I have ghee, or fried snacks like samosa and pakora?',
    aliases: [
      'ghee', 'oil', 'tel', 'cooking oil', 'mustard oil', 'sarson', 'coconut oil', 'butter', 'makhan', 'vanaspati', 'dalda', 'fried', 'fried food',
      'deep fried', 'frying', 'samosa', 'pakora', 'pakoda', 'bhajji', 'bhaji', 'kachori', 'vada', 'puri', 'poori', 'bhature', 'fat', 'fats',
      'घी', 'तेल', 'समोसा', 'पकोड़ा',
    ],
    answer: ['fd-oil', 'fd-cooking'],
    notes: ['fd-healthy-meal'],
    actions: ['fd-healthy-snacks', 'salt-hidden-indian', 'fd-processed'],
    cautions: ['fd-personal-plan'],
    related: ['card-plate', 'card-hidden-salt'],
    action: MEALS,
  }),
  card({
    id: 'card-drinks',
    topics: ['food-diabetes', 'water'],
    title: 'Drinks, sweets and fruit',
    question: 'What should I drink, and can I have sweets or fruit?',
    aliases: [
      'juice', 'cold drink', 'soft drink', 'cola', 'chai', 'tea', 'coffee', 'sugar', 'mithai', 'sweets', 'dessert', 'fruit', 'mango', 'banana',
      'jaggery', 'gur', 'honey', 'drinks', 'jalebi', 'gulab jamun', 'halwa', 'kheer', 'ladoo', 'laddoo', 'barfi', 'lassi', 'sharbat',
      'shakkar', 'cheeni', 'chini', 'aam', 'kela', 'चीनी', 'मिठाई', 'आम', 'केला',
    ],
    answer: ['fd-water-first', 'fd-added-sugar'],
    actions: ['fd-fruit-whole', 'fd-processed', 'water-hot-weather'],
    cautions: ['fd-personal-plan', 'water-plan-first'],
    related: ['card-plate', 'card-water-amount'],
  }),
  card({
    id: 'card-after-meal-walk',
    topics: ['food-diabetes', 'habits'],
    title: 'Walking after meals',
    question: 'Does a walk after eating help my blood sugar?',
    aliases: ['walk after food', 'after-meal walk', 'post-meal walk', 'after dinner walk', 'evening walk', 'stroll', 'sugar after meals', 'post meal sugar', 'tahalna'],
    answer: ['walk-meals-study', 'walk-meals-limits'],
    actions: ['walk-meals-try', 'act-start-small', 'act-talk-test'],
    cautions: ['walk-carry-sugar', 'walk-feet', 'walk-foot-wound', 'act-check-first'],
    related: ['card-steps', 'card-sitting-breaks'],
    action: WALK,
  }),
  card({
    id: 'card-supplements',
    topics: ['food-diabetes'],
    title: 'Home remedies and pills',
    question: 'Do cinnamon, turmeric or other supplements help blood sugar?',
    aliases: [
      'dalchini', 'cinnamon', 'haldi', 'turmeric', 'curcumin', 'aloe vera', 'chromium', 'magnesium', 'herbal', 'herbs', 'ayurvedic',
      'home remedy', 'home remedies', 'supplement', 'supplements', 'methi', 'fenugreek', 'karela juice', 'jamun', 'jamun seeds', 'giloy', 'neem',
    ],
    answer: ['fd-supplements', 'd-diabetes'],
    actions: ['fd-plate-method', 'fd-fibre', 'walk-meals-try'],
    cautions: ['fd-tell-supplements', 'sglt2-keto'],
    related: ['card-plate', 'card-b12-test', 'card-d-test'],
  }),
  card({
    id: 'card-fasting',
    topics: ['food-diabetes'],
    title: 'Fasting and your medicines',
    question: 'Is it safe to fast with diabetes?',
    aliases: [
      'fasting', 'fast', 'vrat', 'upvas', 'upavas', 'roza', 'rozas', 'ramadan', 'ramzan', 'navratri', 'ekadashi',
      'karva chauth', 'keto', 'ketogenic', 'low carb', 'ketones', 'ketoacidosis', 'dka', 'skip meals', 'skipping meals',
      'intermittent fasting', 'insulin', 'sulfonylurea', 'sglt2', 'व्रत', 'उपवास', 'रोज़ा',
    ],
    answer: ['fast-ada'],
    emergencies: ['sglt2-dka-signs'],
    actions: ['fast-plan', 'fd-meds-timing', 'sglt2-plan'],
    cautions: ['fast-lows'],
    related: ['card-plate', 'card-alcohol', 'card-glucose-checks'],
  }),

  // Checking your sugar. One answer for everyone, each medicine marked "For
  // you" where it applies; a further card for each insulin regimen, so the two
  // regimens see different advice in the topic itself (codex-acceptance J12).
  card({
    id: 'card-glucose-checks',
    topics: ['food-diabetes'],
    title: 'How often to check your sugar',
    question: 'How often should I check my blood sugar at home?',
    aliases: [
      'glucose', 'blood glucose', 'blood sugar', 'sugar', 'sugar level', 'sugar test', 'glucose test', 'sugar check', 'check sugar',
      'checking sugar', 'how often', 'monitoring', 'glucose monitoring', 'self monitoring', 'smbg', 'glucometer', 'meter', 'sugar machine',
      'finger prick', 'fingerstick', 'strips', 'fasting sugar', 'pp sugar', 'random sugar', 'hba1c', 'a1c', 'insulin', 'basal',
      'sulfonylurea', 'gliclazide', 'glimepiride', 'meglitinide', 'metformin', 'cgm', 'sensor', 'शुगर', 'शुगर टेस्ट', 'ब्लड शुगर', 'ग्लूकोज',
    ],
    answer: ['gl-plan', 'gl-hba1c'],
    emergencies: GLUCOSE_HELP,
    notes: ['gl-no-hypo-guides', 'gl-cost'],
    actions: ['gl-no-hypo-meds', 'gl-su', 'gl-basal', 'gl-mealtime', 'gl-record'],
    cautions: ['gl-tell-range', 'gl-tell-lows', 'walk-carry-sugar', 'gl-ill'],
    related: ['card-glucose-basal', 'card-glucose-meals', 'card-glucose-record', 'card-fasting'],
    action: ADD_GLUCOSE,
  }),
  card({
    id: 'card-glucose-basal',
    topics: ['food-diabetes'],
    title: 'Checks with long-acting insulin',
    question: 'How often should I check my sugar on long-acting insulin?',
    showWhen: 'basalInsulin',
    aliases: [
      'basal', 'basal insulin', 'long acting insulin', 'long-acting insulin', 'once a day insulin', 'night insulin', 'glargine', 'degludec',
      'detemir', 'insulin', 'fasting sugar', 'fasting check', 'glucose', 'blood sugar', 'sugar', 'monitoring',
    ],
    answer: ['gl-basal'],
    emergencies: GLUCOSE_HELP,
    notes: ['gl-cgm'],
    actions: ['gl-symptoms', 'gl-record', 'gl-bring'],
    cautions: ['gl-no-change', 'gl-tell-lows', 'walk-carry-sugar'],
    related: ['card-glucose-checks', 'card-glucose-record'],
    action: ADD_GLUCOSE,
  }),
  card({
    id: 'card-glucose-meals',
    topics: ['food-diabetes'],
    title: 'Checks with insulin at meals',
    question: 'When should I check my sugar if I take insulin before meals?',
    showWhen: 'mealtimeInsulin',
    aliases: [
      'mealtime insulin', 'meal insulin', 'bolus', 'rapid acting insulin', 'short acting insulin', 'several injections', 'multiple injections',
      'mdi', 'basal bolus', 'insulin pump', 'pump', 'insulin', 'bedtime', 'glucose', 'blood sugar', 'sugar', 'monitoring',
    ],
    answer: ['gl-mealtime'],
    emergencies: GLUCOSE_HELP,
    notes: ['gl-cgm'],
    actions: ['gl-symptoms', 'gl-record', 'gl-bring'],
    cautions: ['gl-no-change', 'gl-tell-lows', 'walk-carry-sugar'],
    related: ['card-glucose-checks', 'card-glucose-record'],
    action: ADD_GLUCOSE,
  }),
  card({
    id: 'card-glucose-record',
    topics: ['food-diabetes'],
    title: 'Writing down your readings',
    question: 'What should I write down, and when should I call my care team?',
    aliases: [
      'record', 'records', 'log', 'logbook', 'sugar log', 'sugar diary', 'glucose log', 'diary', 'notebook', 'chart', 'write down', 'reading',
      'readings', 'before meal', 'after meal', 'post meal', 'pp sugar', 'fasting sugar', 'when to call', 'call doctor', 'care team',
      'low sugar', 'hypo', 'hypoglycaemia', 'hypoglycemia', 'high sugar', 'glucose', 'blood sugar', 'sugar', 'strips', 'test strips',
    ],
    answer: ['gl-record', 'gl-meal-timing'],
    emergencies: [...GLUCOSE_HELP, 'sglt2-dka-signs'],
    actions: ['gl-note-more', 'gl-bring', 'gl-strips'],
    cautions: ['gl-tell-range', 'gl-tell-lows', 'gl-ill'],
    related: ['card-glucose-checks', 'card-fasting'],
    action: ADD_GLUCOSE,
  }),
  card({
    id: 'card-waist',
    topics: ['food-diabetes', 'food-bp'],
    title: 'Your waist size',
    question: 'What waist size means a higher risk for Indian adults?',
    aliases: [
      'waist', 'waist size', 'waistline', 'waist circumference', 'tummy', 'tummy fat', 'belly', 'belly fat', 'pet', 'paunch', 'tond',
      'abdominal obesity', 'central obesity', 'obesity', 'overweight', 'weight', 'weight loss', 'bmi', 'body mass index', 'measuring tape',
      'inch tape', 'kamar', 'कमर', 'पेट', 'तोंद', 'मोटापा',
    ],
    answer: ['waist-rssdi', 'waist-nin'],
    notes: ['waist-same-line', 'waist-why', 'bmi-indian'],
    actions: ['waist-measure', 'waist-keep', 'waist-slow', 'waist-visits'],
    cautions: ['fd-personal-plan'],
    related: ['card-plate', 'card-activity'],
    action: ADD_WAIST,
  }),

  // Food & blood pressure
  card({
    id: 'card-salt-limit',
    topics: ['food-bp'],
    title: 'How much salt?',
    question: 'How much salt can I have in a day?',
    aliases: ['namak', 'salt', 'sodium', 'teaspoon', 'bp diet', 'blood pressure diet', 'hypertension diet', 'low salt'],
    answer: ['salt-limit', 'salt-why'],
    notes: ['salt-ada'],
    actions: ['salt-table', 'salt-flavour', 'salt-iodised'],
    cautions: ['bp-own-targets', 'hf-salt-fluid'],
    related: ['card-hidden-salt', 'card-salt-types', 'card-bp-eating', 'card-bp-numbers'],
  }),
  card({
    id: 'card-hidden-salt',
    topics: ['food-bp'],
    title: 'Where salt hides',
    question: 'Which foods have hidden salt?',
    aliases: [
      'achar', 'pickle', 'papad', 'papadum', 'appalam', 'namkeen', 'bhujia', 'chips', 'farsan', 'sauce', 'ketchup', 'bread', 'pav',
      'instant noodles', 'packaged food', 'baking soda', 'processed food', 'sev', 'mixture', 'chaat masala', 'अचार', 'पापड़', 'नमकीन',
    ],
    answer: ['salt-hidden-indian', 'salt-hidden-packaged'],
    actions: ['salt-baking-soda', 'fd-processed', 'salt-flavour'],
    cautions: ['bp-own-targets'],
    related: ['card-salt-limit', 'card-salt-types'],
  }),
  card({
    id: 'card-salt-types',
    topics: ['food-bp'],
    title: 'Rock salt, low-sodium salt',
    question: 'Is sendha namak or a low-sodium salt better for me?',
    aliases: ['sendha namak', 'rock salt', 'pink salt', 'himalayan salt', 'kala namak', 'black salt', 'lona', 'low sodium salt', 'salt substitute', 'potassium salt', 'lite salt'],
    answer: ['salt-rock-black', 'lsss-what'],
    actions: ['salt-limit', 'salt-flavour', 'salt-table'],
    cautions: ['lsss-caution', 'lsss-kidney', 'bp-meds-potassium'],
    related: ['card-salt-limit', 'card-bp-eating'],
  }),
  card({
    id: 'card-bp-eating',
    topics: ['food-bp'],
    title: 'Eating for blood pressure',
    question: 'What should I eat to help my blood pressure?',
    aliases: ['dash', 'dash diet', 'bp', 'high bp', 'hypertension', 'blood pressure', 'potassium', 'heart healthy'],
    answer: ['bp-dash', 'bp-dash-what'],
    actions: ['bp-potassium-foods', 'salt-limit', 'fd-veg-every-meal', 'alc-bp', 'salt-flavour'],
    cautions: ['bp-own-targets', 'bp-potassium-kidney'],
    related: ['card-salt-limit', 'card-alcohol', 'card-bp-measure'],
    action: MEALS,
  }),
  card({
    id: 'card-bp-measure',
    topics: ['food-bp'],
    title: 'Measuring your blood pressure at home',
    question: 'How do I check my blood pressure at home?',
    aliases: [
      'bp', 'bp machine', 'bp monitor', 'bp check', 'check bp', 'home bp', 'blood pressure machine', 'blood pressure monitor', 'monitor',
      'monitoring', 'cuff', 'measure', 'measuring', 'reading', 'readings', 'digital bp', 'wrist monitor', 'hypertension', 'high bp',
      'बीपी', 'बीपी मशीन', 'रक्तचाप',
    ],
    answer: ['bpm-why', 'bpm-device'],
    emergencies: ['emergency-heart', 'stroke-signs', 'bp-severe-emergency', 'bp-severe-recheck'],
    notes: ['bpm-week'],
    actions: ['bpm-before', 'bpm-sit', 'bpm-arm', 'bpm-two-readings', 'bpm-bring'],
    cautions: ['bpm-meds', 'bp-own-targets'],
    related: ['card-bp-numbers', 'card-bp-eating', 'card-salt-limit'],
    action: ADD_BP,
  }),
  card({
    id: 'card-bp-numbers',
    topics: ['food-bp'],
    title: 'What blood pressure numbers mean',
    question: 'What do my blood pressure readings mean?',
    aliases: [
      'bp', 'bp reading', 'bp range', 'normal bp', 'high bp', 'bp target', 'bp goal', 'target', 'goal', 'normal', 'range', '135/85', '140/90',
      '130/80', 'nice', 'ada', 'hypertension', 'top number', 'bottom number', 'systolic', 'diastolic', 'बीपी', 'रक्तचाप',
    ],
    answer: ['bpn-nice', 'bpn-ada'],
    emergencies: ['emergency-heart', 'stroke-signs', 'bp-severe-emergency', 'bp-severe-recheck'],
    notes: ['bpn-which', 'bpn-one-reading', 'bpn-nice-target'],
    actions: ['bpn-ask-goal', 'bpm-two-readings', 'bpm-bring'],
    cautions: ['bp-own-targets', 'bpm-meds'],
    related: ['card-bp-measure', 'card-bp-eating'],
    action: ADD_BP,
  }),

  // Vitamin B12
  card({
    id: 'card-b12-why',
    topics: ['b12'],
    title: 'B12 and metformin',
    question: 'Why does vitamin B12 matter for me?',
    aliases: ['b12', 'b 12', 'vitamin b12', 'cobalamin', 'metformin', 'diabetes medicine', 'tingling', 'numbness', 'pins and needles', 'tiredness', 'pregabalin', 'omeprazole', 'acidity tablets'],
    answer: ['b12-metformin', 'b12-metformin-yearly'],
    emergencies: ['stroke-signs', 'back-weakness'],
    notes: ['b12-other-medicines'],
    actions: ['b12-ask-monitoring', 'b12-ask-test', 'fd-tell-supplements'],
    cautions: ['b12-doctor-decides', 'b12-numbness-check'],
    related: ['card-b12-food', 'card-b12-test'],
  }),
  card({
    id: 'card-b12-food',
    topics: ['b12'],
    title: 'Foods with B12',
    question: 'How can I get more B12 from food?',
    aliases: [
      'b12 food', 'b12 foods', 'vegetarian b12', 'veg b12', 'milk', 'doodh', 'dahi', 'curd', 'yogurt', 'yoghurt', 'paneer', 'panner', 'panir',
      'eggs', 'egg', 'anda', 'ande', 'fish', 'machli', 'machhli', 'chicken', 'murga', 'mutton', 'meat', 'fortified', 'vegan', 'पनीर', 'दूध',
    ],
    answer: ['b12-sources', 'b12-plants'],
    notes: ['b12-vegetarian-hard', 'b12-low-animal-risk'],
    actions: ['b12-variety', 'b12-label', 'b12-ask-test'],
    cautions: ['b12-doctor-decides'],
    related: ['card-b12-why', 'card-b12-test'],
  }),
  card({
    id: 'card-b12-test',
    topics: ['b12'],
    title: 'B12 tests and supplements',
    question: 'Do I need a B12 test or supplement?',
    aliases: ['b12 test', 'b12 level', 'b12 injection', 'b12 tablet', 'methylcobalamin', 'supplement', 'deficiency', 'low b12', 'anaemia', 'anemia'],
    answer: ['b12-when-tested', 'b12-metformin'],
    emergencies: ['stroke-signs', 'back-weakness'],
    notes: ['b12-metformin-yearly', 'b12-symptoms', 'b12-slow'],
    actions: ['b12-ask-test', 'b12-ask-monitoring', 'fd-tell-supplements'],
    cautions: ['b12-doctor-decides', 'b12-numbness-check'],
    related: ['card-b12-why', 'card-b12-food'],
  }),

  // Vitamin D
  card({
    id: 'card-d-get',
    topics: ['vitamin-d'],
    title: 'Getting vitamin D',
    question: 'How can I get more vitamin D?',
    aliases: ['vitamin d', 'vit d', 'sunlight', 'sun', 'dhoop', 'sunshine', 'fish', 'egg yolk', 'mushroom', 'mushrooms', 'fortified'],
    answer: ['d-sun', 'd-foods'],
    notes: ['d-sun-varies', 'd-indoors', 'd-vegan'],
    actions: ['d-get-outside', 'd-sun-skin', 'd-label'],
    cautions: ['d-doctor-decides'],
    related: ['card-d-test'],
  }),
  card({
    id: 'card-d-test',
    topics: ['vitamin-d'],
    title: 'Vitamin D tests',
    question: 'Should I get tested or take vitamin D?',
    aliases: ['vitamin d test', 'vitamin d level', 'vitamin d tablet', 'sachet', 'cholecalciferol', 'deficiency', 'low vitamin d', 'supplement'],
    answer: ['d-no-routine-test', 'd-diabetes'],
    notes: ['d-at-risk'],
    actions: ['d-ask-test', 'fd-tell-supplements', 'd-get-outside'],
    cautions: ['d-too-much', 'd-thiazide', 'd-doctor-decides'],
    related: ['card-d-get', 'card-supplements'],
  }),

  // Desk setup & sitting
  card({
    id: 'card-desk-setup',
    topics: ['desk'],
    title: 'Setting up your desk',
    question: 'How should I set up my chair, desk and screen?',
    aliases: ['ergonomics', 'chair', 'office chair', 'desk', 'table', 'monitor', 'screen', 'screen height', 'laptop', 'work from home', 'wfh', 'lumbar support', 'back support', 'cushion', 'towel', 'footrest', 'keyboard'],
    answer: ['desk-screen', 'desk-lumbar'],
    notes: ['desk-back-link'],
    actions: ['desk-feet', 'desk-arms', 'desk-centred', 'desk-laptop', 'desk-text-size'],
    cautions: ['desk-report-early'],
    related: ['card-posture', 'card-sitting-breaks'],
  }),
  card({
    id: 'card-posture',
    topics: ['desk'],
    title: 'Is there a right posture?',
    question: 'How do I sit up straight?',
    aliases: ['posture', 'sit straight', 'sit up straight', 'sitting posture', 'right posture', 'correct posture', 'slouch', 'slouching', 'hunch', 'straight back', 'standing desk', 'neck pain'],
    answer: ['desk-no-single-posture', 'desk-postures'],
    actions: ['desk-ways-to-change', 'desk-lumbar', 'desk-eyes'],
    cautions: ['desk-report-early'],
    related: ['card-desk-setup', 'card-sitting-breaks'],
    action: STRETCH,
  }),
  card({
    id: 'card-sitting-breaks',
    topics: ['desk', 'habits'],
    title: 'Getting up from your desk',
    question: 'How often should I get up from sitting?',
    aliases: ['sitting', 'sitting too long', 'sitting all day', 'break', 'breaks', 'stand up', 'sedentary', 'office', 'move more', 'reminder'],
    answer: ['sit-30', 'sit-hourly'],
    notes: ['sit-dempsey', 'sit-short-often'],
    actions: ['sit-nin-tips', 'sit-any-movement', 'desk-ways-to-change'],
    cautions: ['desk-report-early'],
    related: ['card-posture', 'card-after-meal-walk'],
    action: { label: 'Set a reminder to move', to: ROUTES.reminders, hideWhen: 'footWound' },
  }),

  // Water
  card({
    id: 'card-water-amount',
    topics: ['water'],
    title: 'How much water?',
    question: 'How much water should I drink?',
    aliases: ['paani', 'pani', 'water', 'hydration', 'glasses', 'litres', 'liters', 'thirst', 'dehydration', 'drink water'],
    // Generic "drink more" advice is withheld with a kidney or heart condition.
    hideWhen: 'fluidCaution',
    answer: ['water-amount', 'water-more'],
    actions: ['fd-water-first', 'water-hot-weather', 'water-safe'],
    cautions: ['water-plan-first'],
    related: ['card-drinks', 'card-water-limit'],
    action: { label: 'Set water reminders', to: ROUTES.reminders },
    furtherReading: ['nhs-water'],
  }),
  card({
    id: 'card-water-limit',
    topics: ['water'],
    title: 'Fluid limits',
    question: 'How much should I drink with kidney or heart disease?',
    aliases: ['fluid restriction', 'fluid limit', 'kidney', 'kidney disease', 'ckd', 'heart failure', 'swelling', 'oedema', 'edema', 'water limit'],
    answer: ['water-kidney', 'hf-salt-fluid'],
    emergencies: ['emergency-heart', 'stroke-signs', 'fluid-swelling'],
    actions: ['fluid-ask-amount', 'fluid-salt', 'water-coconut'],
    cautions: ['water-plan-first'],
    related: ['card-drinks', 'card-salt-limit'],
  }),

  // Sleep
  card({
    id: 'card-sleep-hours',
    topics: ['sleep'],
    title: 'How much sleep?',
    question: 'How much sleep do I need?',
    aliases: ['neend', 'sleep', 'hours of sleep', 'tired', 'tiredness', 'insomnia', 'cant sleep', 'sleepless'],
    answer: ['sleep-hours', 'sleep-quality'],
    notes: ['sleep-ada-screen'],
    actions: ['sleep-same-times', 'sleep-active', 'sleep-ada-routine'],
    cautions: ['sleep-see-doctor'],
    related: ['card-sleep-better', 'card-snoring'],
    furtherReading: ['nhs-insomnia'],
  }),
  card({
    id: 'card-sleep-better',
    topics: ['sleep', 'habits'],
    title: 'Sleeping better',
    question: 'How can I sleep better?',
    aliases: ['bedtime', 'wind down', 'sleep routine', 'sleep hygiene', 'screens', 'phone at night', 'chai at night', 'coffee', 'caffeine'],
    answer: ['sleep-same-times', 'sleep-room'],
    actions: ['sleep-screens', 'sleep-food-caffeine', 'sleep-active'],
    cautions: ['sleep-see-doctor'],
    related: ['card-sleep-hours', 'card-snoring'],
    furtherReading: ['nhs-insomnia'],
  }),
  card({
    id: 'card-snoring',
    topics: ['sleep'],
    title: 'Snoring and sleep apnoea',
    question: 'Could my snoring be a problem?',
    aliases: ['snoring', 'snore', 'kharrate', 'sleep apnea', 'sleep apnoea', 'osa', 'gasping', 'daytime sleepiness', 'cpap'],
    answer: ['apnoea-signs'],
    notes: ['sleep-ada-screen'],
    actions: ['apnoea-ask-someone', 'sleep-food-caffeine', 'sleep-same-times'],
    cautions: ['apnoea-tell-doctor'],
    related: ['card-sleep-hours'],
  }),

  // Movement & your back
  card({
    id: 'card-keep-moving',
    topics: ['back'],
    title: 'Moving with back pain',
    question: 'Should I keep moving with sciatica or back pain?',
    aliases: ['sciatica', 'back pain', 'kamar dard', 'kamar', 'lower back', 'slipped disc', 'disc', 'nerve pain', 'leg pain', 'rest', 'bed rest', 'belt', 'lumbar belt', 'back belt', 'stretch', 'stretching', 'yoga'],
    answer: ['back-normal-activities', 'back-exercise'],
    emergencies: BACK_RED_FLAGS,
    actions: ['act-start-small', 'back-no-belts', 'act-talk-test'],
    cautions: ['back-not-controlled', 'back-see-doctor', 'back-changed'],
    related: ['card-sciatica-course', 'card-walking-back', 'card-activity'],
    action: STRETCH,
  }),
  card({
    id: 'card-sciatica-course',
    topics: ['back'],
    title: 'How sciatica gets better',
    question: 'How long does sciatica take to get better?',
    aliases: [
      'sciatica', 'how long', 'recovery', 'recover', 'get better', 'getting better', 'heal', 'healing', 'prognosis', 'go away', 'nerve pain',
      'leg pain', 'disc', 'slipped disc', 'disc bulge', 'mri', 'scan', 'come back', 'coming back', 'recurrence', 'flare', 'flare-up',
      'bed rest', 'साइटिका', 'कमर दर्द',
    ],
    answer: ['sci-gets-better', 'sci-some-longer'],
    emergencies: BACK_RED_FLAGS,
    notes: ['sci-comes-back', 'sci-bed-rest', 'sci-scan'],
    actions: ['back-normal-activities', 'back-exercise', 'act-start-small'],
    cautions: ['sci-not-easing', 'back-not-controlled', 'back-changed'],
    related: ['card-keep-moving', 'card-walking-back'],
    action: STRETCH,
  }),
  card({
    id: 'card-walking-back',
    topics: ['back'],
    title: 'Walking and your back',
    question: 'Does walking help my back?',
    aliases: ['walking', 'walk', 'back pain coming back', 'recurrence', 'walkback'],
    answer: ['back-walkback', 'back-walkback-limits'],
    emergencies: BACK_RED_FLAGS,
    actions: ['act-start-small', 'steps-build', 'act-talk-test'],
    cautions: ['walk-feet', 'walk-foot-wound', 'back-changed'],
    related: ['card-steps', 'card-keep-moving'],
    action: WALK,
  }),
  card({
    id: 'card-activity',
    topics: ['back'],
    title: 'How much activity?',
    question: 'How much exercise should I do?',
    aliases: ['exercise', 'workout', 'activity', 'minutes a week', 'strength training', 'weights', 'gym', 'yoga', 'vyayam'],
    answer: ['act-who', 'act-nin'],
    emergencies: BACK_RED_FLAGS,
    notes: ['act-ada'],
    actions: ['act-start-small', 'act-talk-test', 'sit-any-movement'],
    cautions: ['act-check-first'],
    related: ['card-steps', 'card-keep-moving'],
  }),
  card({
    id: 'card-steps',
    topics: ['back'],
    title: 'How many steps a day?',
    question: 'How many steps should I walk a day?',
    aliases: ['steps', 'step count', '10000 steps', '7000 steps', 'pedometer', 'kadam'],
    answer: ['steps-ding', 'steps-realistic'],
    emergencies: BACK_RED_FLAGS,
    notes: ['steps-more'],
    actions: ['steps-build', 'walk-meals-try', 'sit-any-movement'],
    cautions: ['walk-feet', 'walk-foot-wound', 'act-check-first'],
    related: ['card-activity', 'card-walking-back'],
    action: WALK,
  }),

  // Daily habits
  card({
    id: 'card-alcohol',
    topics: ['habits'],
    title: 'Alcohol',
    question: 'Is any amount of alcohol safe?',
    aliases: ['alcohol', 'drink', 'drinking', 'beer', 'whisky', 'whiskey', 'rum', 'wine', 'daru', 'sharab', 'peg'],
    answer: ['alc-no-safe', 'alc-dont-start'],
    notes: ['alc-nin'],
    actions: ['alc-bp', 'alc-sglt2', 'sleep-food-caffeine'],
    cautions: ['alc-delayed-lows'],
    related: ['card-tobacco', 'card-bp-eating'],
  }),
  card({
    id: 'card-tobacco',
    topics: ['habits'],
    title: 'Tobacco and vaping',
    question: 'How do I stop smoking or chewing tobacco?',
    aliases: ['smoking', 'cigarette', 'cigarettes', 'bidi', 'beedi', 'gutka', 'gutkha', 'khaini', 'paan masala', 'zarda', 'hookah', 'vape', 'vaping', 'e-cigarette', 'quit smoking', 'tobacco'],
    answer: ['tob-avoid', 'tob-benefit'],
    notes: ['tob-chewed'],
    actions: ['tob-help', 'tob-tell-doctor', 'tob-vape'],
    cautions: ['tob-meds-doctor'],
    related: ['card-alcohol'],
  }),
];
