import type { FurtherReading, Source } from './schema';

/**
 * Every document a claim cites. Each was read at its primary source on the
 * accessed date; the research files under `docs/research/` hold the wider
 * search that led to them.
 *
 * Licences decide how these may be used (board D32): we summarise facts and
 * principles in our own words and cite the exact place, and reproduce no
 * guideline text, table or figure. ADA is cited by recommendation number.
 */
export const SOURCES: Source[] = [
  {
    id: 'nin-dgi-2024',
    organisation: 'ICMR–National Institute of Nutrition',
    short: 'ICMR-NIN',
    title: 'Dietary Guidelines for Indians',
    edition: '2024',
    url: 'https://www.nin.res.in/dietaryguidelines/pdfjs/locale/DGI_2024.pdf',
    locator: 'Guidelines 1, 2, 6–11 and 13–15; Annexures I, II and IV',
    jurisdiction: 'India',
    population: 'Indians of all ages; the sample days are for healthy adults with a normal BMI',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'rssdi-esi-2020',
    organisation: 'RSSDI-ESI Consensus Group (Chawla et al., Indian Journal of Endocrinology and Metabolism)',
    short: 'RSSDI-ESI',
    title: 'RSSDI-ESI Clinical Practice Recommendations for the Management of Type 2 Diabetes Mellitus 2020',
    edition: 'Indian J Endocrinol Metab 2020;24(1):1–122',
    url: 'https://doi.org/10.4103/ijem.IJEM_225_20',
    locator: 'Glycaemic monitoring: recommended care and self-monitoring of blood glucose (Tables 19 and 22); Obesity and type 2 diabetes mellitus: recommended care and identification of obesity',
    jurisdiction: 'India',
    population: 'Indian adults with type 2 diabetes',
    accessed: '2026-10-08',
    kind: 'guideline',
    licence: 'RSSDI-ESI 2020: © 2020 Indian Journal of Endocrinology and Metabolism, open access under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 licence; summarised here, not reproduced.',
  },
  {
    id: 'icmr-t2dm-2018',
    organisation: 'Indian Council of Medical Research',
    short: 'ICMR',
    title: 'ICMR Guidelines for Management of Type 2 Diabetes',
    edition: '2018',
    url: 'https://www.icmr.gov.in/icmrobject/custom_data/pdf/resource-guidelines/ICMR_GuidelinesType2diabetes2018_0.pdf',
    locator: 'Section 5.2, self-monitoring of blood glucose (pp. 14–15); section 7.1.2, sulphonylureas (p. 29)',
    jurisdiction: 'India',
    population: 'Adults with type 2 diabetes in India',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'ada-soc-2026-s5',
    organisation: 'American Diabetes Association',
    short: 'ADA',
    title: 'Standards of Care in Diabetes—2026, Section 5: Facilitating Positive Health Behaviors and Well-being',
    edition: 'Diabetes Care 2026;49(Suppl 1)',
    url: 'https://doi.org/10.2337/dc26-S005',
    locator: 'Recommendations in section 5, cited by number on each answer',
    jurisdiction: 'United States; used internationally',
    population: 'People with diabetes or at risk of it',
    accessed: '2026-10-08',
    kind: 'guideline',
    citeBy: 'recommendation',
  },
  {
    id: 'ada-soc-2026-s3',
    organisation: 'American Diabetes Association',
    short: 'ADA',
    title: 'Standards of Care in Diabetes—2026, Section 3: Prevention or Delay of Diabetes and Associated Comorbidities',
    edition: 'Diabetes Care 2026;49(Suppl 1)',
    url: 'https://doi.org/10.2337/dc26-S003',
    locator: 'Recommendation 3.10',
    jurisdiction: 'United States; used internationally',
    population: 'People with prediabetes or diabetes',
    accessed: '2026-10-08',
    kind: 'guideline',
    citeBy: 'recommendation',
  },
  {
    id: 'ada-soc-2026-s6',
    organisation: 'American Diabetes Association',
    short: 'ADA',
    title: 'Standards of Care in Diabetes—2026, Section 6: Glycemic Goals, Hypoglycemia, and Hyperglycemic Crises',
    edition: 'Diabetes Care 2026;49(Suppl 1)',
    url: 'https://doi.org/10.2337/dc26-S006',
    locator: 'Recommendations 6.1, 6.2, 6.10, 6.16 and 6.19',
    jurisdiction: 'United States; used internationally',
    population: 'People with diabetes',
    accessed: '2026-10-08',
    kind: 'guideline',
    citeBy: 'recommendation',
  },
  {
    id: 'ada-soc-2026-s7',
    organisation: 'American Diabetes Association',
    short: 'ADA',
    title: 'Standards of Care in Diabetes—2026, Section 7: Diabetes Technology',
    edition: 'Diabetes Care 2026;49(Suppl 1)',
    url: 'https://doi.org/10.2337/dc26-S007',
    locator: 'Recommendations 7.10 to 7.13',
    jurisdiction: 'United States; used internationally',
    population: 'People with diabetes who check their glucose with a meter or sensor',
    accessed: '2026-10-08',
    kind: 'guideline',
    citeBy: 'recommendation',
  },
  {
    id: 'ada-soc-2026-s10',
    organisation: 'American Diabetes Association',
    short: 'ADA',
    title: 'Standards of Care in Diabetes—2026, Section 10: Cardiovascular Disease and Risk Management',
    edition: 'Diabetes Care 2026;49(Suppl 1)',
    url: 'https://doi.org/10.2337/dc26-S010',
    locator: 'Recommendations 10.1 to 10.5 and 10.11',
    jurisdiction: 'United States; used internationally',
    population: 'People with diabetes and high blood pressure',
    accessed: '2026-10-08',
    kind: 'guideline',
    citeBy: 'recommendation',
  },
  {
    id: 'ada-diabetes-plate',
    organisation: 'American Diabetes Association (Diabetes Food Hub)',
    short: 'ADA',
    title: 'What is the Diabetes Plate?',
    edition: '14 May 2026',
    url: 'https://diabetesfoodhub.org/blog/what-diabetes-plate',
    locator: 'Steps 1–4 and “What about combination foods?”',
    jurisdiction: 'United States',
    population: 'Adults with diabetes',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'who-sodium-2026',
    organisation: 'World Health Organization',
    short: 'WHO',
    title: 'Sodium reduction (fact sheet)',
    edition: '11 May 2026',
    url: 'https://www.who.int/news-room/fact-sheets/detail/sodium-reduction',
    locator: 'Overview; Recommendations for reducing sodium; How can you reduce your sodium intake?',
    jurisdiction: 'International',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'who-lsss-2025',
    organisation: 'World Health Organization',
    short: 'WHO',
    title: 'Use of lower-sodium salt substitutes: WHO guideline',
    edition: '27 January 2025',
    url: 'https://www.who.int/publications/i/item/9789240105591',
    locator: 'Executive summary: background, the evidence and the scope of the recommendation',
    jurisdiction: 'International',
    population: 'Adults in general populations, excluding people with kidney impairment',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'who-pa-2020',
    organisation: 'World Health Organization',
    short: 'WHO',
    title: 'WHO 2020 guidelines on physical activity and sedentary behaviour (Bull et al., Br J Sports Med)',
    edition: '2020',
    url: 'https://doi.org/10.1136/bjsports-2020-102955',
    locator: 'Table 4 (adults 18–64, including chronic conditions) and the text that introduces it',
    jurisdiction: 'International',
    population: 'Adults, including people living with chronic conditions',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'who-alcohol-2023',
    organisation: 'World Health Organization, Regional Office for Europe',
    short: 'WHO',
    title: 'No level of alcohol consumption is safe for our health',
    edition: '4 January 2023',
    url: 'https://www.who.int/europe/news/item/04-01-2023-no-level-of-alcohol-consumption-is-safe-for-our-health',
    locator: 'Headline statement and opening paragraphs',
    jurisdiction: 'Europe; a global health statement',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'ods-b12',
    organisation: 'National Institutes of Health, Office of Dietary Supplements',
    short: 'NIH ODS',
    title: 'Vitamin B12: Fact Sheet for Consumers',
    edition: 'Current consumer fact sheet',
    url: 'https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/',
    locator: 'What foods provide vitamin B12?; Am I getting enough vitamin B12?; What happens if I don’t get enough?; Interactions, including metformin',
    jurisdiction: 'United States',
    population: 'Adults and children',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'ods-vitamin-d',
    organisation: 'National Institutes of Health, Office of Dietary Supplements',
    short: 'NIH ODS',
    title: 'Vitamin D: Fact Sheet for Consumers',
    edition: 'Current consumer fact sheet',
    url: 'https://ods.od.nih.gov/factsheets/VitaminD-Consumer/',
    locator: 'What foods provide vitamin D?; Can I get vitamin D from the sun?; Am I getting enough vitamin D?; Type 2 diabetes; Can vitamin D be harmful?; Interactions',
    jurisdiction: 'United States',
    population: 'Adults and children',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'ods-vitamin-d-hp',
    organisation: 'National Institutes of Health, Office of Dietary Supplements',
    short: 'NIH ODS',
    title: 'Vitamin D: Fact Sheet for Health Professionals',
    edition: 'Current health professional fact sheet',
    url: 'https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/',
    locator: 'Sources of Vitamin D: Sun exposure; Vitamin D Deficiency; Groups at Risk of Vitamin D Inadequacy',
    jurisdiction: 'United States',
    population: 'Health professionals',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'nice-ng239',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Vitamin B12 deficiency in over 16s: identification and management (NG239)',
    edition: 'Published 6 March 2024',
    url: 'https://www.nice.org.uk/guidance/ng239/chapter/recommendations',
    locator: 'Recommendation 1.2.5; Box 1 (symptoms and signs); Box 2 (risk factors)',
    jurisdiction: 'United Kingdom',
    population: 'People over 16',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'endocrine-vitamin-d-2024',
    organisation: 'Endocrine Society',
    short: 'Endocrine Society',
    title: 'Vitamin D for the Prevention of Disease: An Endocrine Society Clinical Practice Guideline',
    edition: '2024',
    url: 'https://www.endocrine.org/clinical-practice-guidelines/vitamin-d-for-prevention-of-disease',
    locator: 'Recommendations 3, 5, 7 and 10',
    jurisdiction: 'International',
    population: 'Generally healthy people without an established reason for vitamin D testing or treatment',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nice-ng59',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Low back pain and sciatica in over 16s: assessment and management (NG59)',
    edition: 'Published 30 November 2016; updated 29 July 2026',
    url: 'https://www.nice.org.uk/guidance/ng59/chapter/Recommendations',
    locator: 'Recommendations 1.1.1, 1.1.4, 1.1.6 and 1.2.1–1.2.3',
    jurisdiction: 'United Kingdom',
    population: 'People over 16 with low back pain, with or without sciatica',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nice-ng59-context',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Low back pain and sciatica in over 16s (NG59): Context',
    edition: 'Published 30 November 2016; updated 29 July 2026',
    url: 'https://www.nice.org.uk/guidance/ng59/chapter/Context',
    locator: 'Context',
    jurisdiction: 'United Kingdom',
    population: 'People over 16 with low back pain, with or without sciatica',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nice-ng28',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Type 2 diabetes in adults: management (NG28)',
    edition: 'Published 2 December 2015; updated 18 February 2026',
    url: 'https://www.nice.org.uk/guidance/ng28/chapter/Blood-glucose-management',
    locator: 'Recommendations 1.5.1 and 1.6.2–1.6.5',
    jurisdiction: 'United Kingdom',
    population: 'Adults with type 2 diabetes',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nice-ng136',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Hypertension in adults: diagnosis and management (NG136)',
    edition: 'Published 28 August 2019; updated 26 February 2026',
    url: 'https://www.nice.org.uk/guidance/ng136/chapter/recommendations',
    locator: 'Recommendations 1.1.3, 1.1.4, 1.2.7, 1.2.8, 1.4.19–1.4.22, 1.5.1 and 1.5.2',
    jurisdiction: 'United Kingdom',
    population: 'Adults with high blood pressure, or being checked for it',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nice-ng127',
    organisation: 'National Institute for Health and Care Excellence',
    short: 'NICE',
    title: 'Suspected neurological conditions: recognition and referral (NG127)',
    edition: 'Published 1 May 2019; updated 2 October 2023',
    url: 'https://www.nice.org.uk/guidance/ng127/chapter/recommendations-for-adults-aged-over-16',
    locator: 'Recommendations 1.7.1–1.7.5 and 1.10.12',
    jurisdiction: 'United Kingdom',
    population: 'Adults over 16',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'acsm-2022',
    organisation: 'American College of Sports Medicine (Kanaley et al., Med Sci Sports Exerc)',
    short: 'ACSM',
    title: 'Exercise/Physical Activity in Individuals with Type 2 Diabetes: A Consensus Statement from the ACSM',
    edition: '2022',
    url: 'https://doi.org/10.1249/MSS.0000000000002800',
    locator: 'Table 4 (precautions) and Table 5 (peripheral neuropathy)',
    jurisdiction: 'United States; used internationally',
    population: 'Adults with type 2 diabetes',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'osha-chairs',
    organisation: 'US Occupational Safety and Health Administration',
    short: 'OSHA',
    title: 'Computer Workstations eTool: Chairs',
    edition: 'Current eTool page',
    url: 'https://www.osha.gov/etools/computer-workstations/components/chairs',
    locator: 'Backrest; Seat; Armrests',
    jurisdiction: 'United States',
    population: 'People who work at a computer',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'osha-monitors',
    organisation: 'US Occupational Safety and Health Administration',
    short: 'OSHA',
    title: 'Computer Workstations eTool: Monitors',
    edition: 'Current eTool page',
    url: 'https://www.osha.gov/etools/computer-workstations/components/monitors',
    locator: 'Viewing distance; Viewing angle; Viewing time',
    jurisdiction: 'United States',
    population: 'People who work at a computer',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'osha-positions',
    organisation: 'US Occupational Safety and Health Administration',
    short: 'OSHA',
    title: 'Computer Workstations eTool: Good Working Positions',
    edition: 'Current eTool page',
    url: 'https://www.osha.gov/etools/computer-workstations/positions',
    locator: 'Neutral body positions; changing position; the four reference postures',
    jurisdiction: 'United States',
    population: 'People who work at a computer',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'osha-work-process',
    organisation: 'US Occupational Safety and Health Administration',
    short: 'OSHA',
    title: 'Computer Workstations eTool: Work Process and Recognition',
    edition: 'Current eTool page',
    url: 'https://www.osha.gov/etools/computer-workstations/work-process',
    locator: 'Micro breaks or rest pauses; recognising signs and symptoms early',
    jurisdiction: 'United States',
    population: 'People who work at a computer',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'hse-dse-posture',
    organisation: 'UK Health and Safety Executive',
    short: 'HSE',
    title: 'Good posture when using display screen equipment',
    edition: 'Current guidance page',
    url: 'https://www.hse.gov.uk/msd/dse/good-posture.htm',
    locator: 'Standard workstation setup; Good posture for laptop use',
    jurisdiction: 'United Kingdom',
    population: 'People who use screens for work',
    accessed: '2026-10-08',
    kind: 'factsheet',
    licence: 'Contains public sector information licensed under the Open Government Licence v3.0.',
  },
  {
    id: 'hse-dse-breaks',
    organisation: 'UK Health and Safety Executive',
    short: 'HSE',
    title: 'Work routine and breaks (display screen equipment)',
    edition: 'Current guidance page',
    url: 'https://www.hse.gov.uk/msd/dse/work-routine.htm',
    locator: 'How long and how often breaks should be',
    jurisdiction: 'United Kingdom',
    population: 'People who use screens for work',
    accessed: '2026-10-08',
    kind: 'factsheet',
    licence: 'Contains public sector information licensed under the Open Government Licence v3.0.',
  },
  {
    id: 'niddk-ckd-eating',
    organisation: 'National Institute of Diabetes and Digestive and Kidney Diseases (NIH)',
    short: 'NIDDK',
    title: 'Healthy Eating for Adults with Chronic Kidney Disease',
    edition: 'Last reviewed January 2025',
    url: 'https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd/healthy-eating-adults-chronic-kidney-disease',
    locator: 'Protein; Liquids; Potassium; Sodium; Track your liquids; Choose the amount and types of protein your body needs; Choose foods that help keep your potassium level in the goal range',
    jurisdiction: 'United States',
    population: 'Adults with chronic kidney disease',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'nhlbi-heart-failure',
    organisation: 'National Heart, Lung, and Blood Institute (NIH)',
    short: 'NHLBI',
    title: 'Living With Heart Failure',
    edition: 'Last updated 24 March 2022',
    url: 'https://www.nhlbi.nih.gov/health/heart-failure/living-with',
    locator: 'Heart-healthy lifestyle changes; Know when to seek help',
    jurisdiction: 'United States',
    population: 'People with heart failure',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'nhlbi-sleep-apnea',
    organisation: 'National Heart, Lung, and Blood Institute (NIH)',
    short: 'NHLBI',
    title: 'Sleep Apnea: Symptoms',
    edition: 'Last updated 9 January 2025',
    url: 'https://www.nhlbi.nih.gov/health/sleep-apnea/symptoms',
    locator: 'Symptoms while asleep and during the day',
    jurisdiction: 'United States',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'cdc-sleep',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'About Sleep',
    edition: 'Published 15 May 2024',
    url: 'https://www.cdc.gov/sleep/about/index.html',
    locator: 'Getting enough sleep; What to do; Sleep quality; Management',
    jurisdiction: 'United States',
    population: 'All ages',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'niddk-low-glucose',
    organisation: 'National Institute of Diabetes and Digestive and Kidney Diseases (NIH)',
    short: 'NIDDK',
    title: 'Low Blood Glucose (Hypoglycemia)',
    edition: 'Last reviewed July 2021',
    url: 'https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia',
    locator: 'What are the symptoms of low blood glucose?; What causes low blood glucose in people with diabetes?; How can I prevent low blood glucose if I have diabetes?; How do I treat low blood glucose?; What if I have severe low blood glucose and can’t treat myself?',
    jurisdiction: 'United States',
    population: 'People with diabetes',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'niddk-managing',
    organisation: 'National Institute of Diabetes and Digestive and Kidney Diseases (NIH)',
    short: 'NIDDK',
    title: 'Managing Diabetes',
    edition: 'Last reviewed October 2023',
    url: 'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes',
    locator: 'A is for the A1C blood glucose test; How can I check my blood glucose level at home?; Devices to help manage diabetes; Recommended targets for blood glucose levels',
    jurisdiction: 'United States',
    population: 'People with diabetes',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'cdc-low-sugar',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'Low Blood Sugar (Hypoglycemia)',
    edition: 'Published 15 May 2024',
    url: 'https://www.cdc.gov/diabetes/about/low-blood-sugar-hypoglycemia.html',
    locator: 'Severe low blood sugar; Symptoms',
    jurisdiction: 'United States',
    population: 'People with diabetes',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'label-empagliflozin',
    organisation: 'US Food and Drug Administration (approved labeling)',
    short: 'FDA label',
    title: 'Jardiance (empagliflozin): Prescribing Information and Medication Guide',
    edition: 'Revised October 2025',
    url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/204629s063lbl.pdf',
    locator: '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis',
    jurisdiction: 'United States',
    population: 'People prescribed empagliflozin, an SGLT2 inhibitor',
    accessed: '2026-10-08',
    kind: 'label',
  },
  {
    id: 'label-dapagliflozin',
    organisation: 'US Food and Drug Administration (approved labeling)',
    short: 'FDA label',
    title: 'Farxiga (dapagliflozin): Prescribing Information and Medication Guide',
    edition: 'Revised June 2026',
    url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/202293s035lbl.pdf',
    locator: '17 Patient Counseling Information: ketoacidosis; Medication Guide: ketoacidosis',
    jurisdiction: 'United States',
    population: 'People prescribed dapagliflozin, an SGLT2 inhibitor',
    accessed: '2026-10-08',
    kind: 'label',
  },
  {
    id: 'cdc-food-safety',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'Safer Food Choices for People With Weakened Immune Systems',
    edition: 'Published 2 May 2024',
    url: 'https://www.cdc.gov/food-safety/foods/weakened-immune-systems.html',
    locator: 'Why it’s important; Safer food choices: vegetables and fruits',
    jurisdiction: 'United States',
    population: 'People with weakened immune systems, including people with diabetes or kidney disease',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'cdc-water-emergency',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'How to Make Water Safe in an Emergency',
    edition: 'Published 19 September 2024',
    url: 'https://www.cdc.gov/water-emergency/about/index.html',
    locator: 'Water with fuel or toxic chemicals in it',
    jurisdiction: 'United States',
    population: 'Everyone',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'nhlbi-dash',
    organisation: 'National Heart, Lung, and Blood Institute (NIH)',
    short: 'NHLBI',
    title: 'DASH Eating Plan',
    edition: 'Last updated 25 February 2026',
    url: 'https://www.nhlbi.nih.gov/education/dash-eating-plan',
    locator: 'Overview',
    jurisdiction: 'United States',
    population: 'Adults, including people with high blood pressure',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'aha-home-bp',
    organisation: 'American Heart Association',
    short: 'AHA',
    title: 'Monitoring Your Blood Pressure at Home',
    edition: 'Last reviewed 14 August 2025',
    url: 'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home',
    locator: 'Who should monitor blood pressure at home?; Choosing a home blood pressure monitor; How to use a home blood pressure monitor; If you get a high blood pressure reading',
    jurisdiction: 'United States',
    population: 'Adults checking their blood pressure at home',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'aha-bp-911',
    organisation: 'American Heart Association',
    short: 'AHA',
    title: 'When To Call 911 About High Blood Pressure',
    edition: 'Last reviewed 14 August 2025',
    url: 'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/hypertensive-crisis-when-you-should-call-911-for-high-blood-pressure',
    locator: 'Severe hypertension; Hypertensive emergency',
    jurisdiction: 'United States (its emergency number is not India’s)',
    population: 'Adults with a very high blood pressure reading',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'aha-bp-2019',
    organisation: 'American Heart Association (Muntner et al., Hypertension)',
    short: 'AHA',
    title: 'Measurement of Blood Pressure in Humans: A Scientific Statement From the American Heart Association',
    edition: '2019',
    url: 'https://doi.org/10.1161/HYP.0000000000000087',
    locator: 'Table 5 (proper seated measurement in the office) and Table 9 (home blood pressure monitoring)',
    jurisdiction: 'United States; used internationally',
    population: 'Adults having their blood pressure measured in a clinic or at home',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'who-waist-2011',
    organisation: 'World Health Organization',
    short: 'WHO',
    title: 'Waist Circumference and Waist–Hip Ratio: Report of a WHO Expert Consultation',
    edition: 'Published 2011 (consultation held 8–11 December 2008)',
    url: 'https://www.who.int/publications/i/item/9789241501491',
    locator: 'Section 2.5, summary and conclusions (p. 7); section 5.2, measurement protocol (pp. 20–21)',
    jurisdiction: 'International',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'guideline',
  },
  {
    id: 'nhlbi-heart-attack',
    organisation: 'National Heart, Lung, and Blood Institute (NIH)',
    short: 'NHLBI',
    title: 'Heart Attack: Symptoms',
    edition: 'Last updated 24 March 2022',
    url: 'https://www.nhlbi.nih.gov/health/heart-attack/symptoms',
    locator: 'What are the symptoms of a heart attack?; When to call 9-1-1',
    jurisdiction: 'United States',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'cdc-stroke',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'Signs and Symptoms of Stroke',
    edition: 'Published 19 May 2026',
    url: 'https://www.cdc.gov/stroke/signs-symptoms/index.html',
    locator: 'What are the signs of stroke in men and women?; When to seek emergency help; What should I do to treat a transient ischemic attack?',
    jurisdiction: 'United States',
    population: 'Everyone',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'niams-back-pain',
    organisation: 'National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIH)',
    short: 'NIAMS',
    title: 'Back Pain',
    edition: 'Last reviewed February 2023',
    url: 'https://www.niams.nih.gov/health-topics/back-pain',
    locator: 'Symptoms of Back Pain',
    jurisdiction: 'United States',
    population: 'Adults with back pain',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'cdc-quit-benefits',
    organisation: 'US Centers for Disease Control and Prevention',
    short: 'CDC',
    title: 'Benefits of Quitting Smoking',
    edition: 'Published 15 May 2024',
    url: 'https://www.cdc.gov/tobacco/about/benefits-of-quitting.html',
    locator: 'Health benefits of quitting smoking',
    jurisdiction: 'United States',
    population: 'People who smoke',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'who-tobacco',
    organisation: 'World Health Organization',
    short: 'WHO',
    title: 'Tobacco (fact sheet)',
    edition: '26 June 2026',
    url: 'https://www.who.int/news-room/fact-sheets/detail/tobacco',
    locator: 'Key facts; Overview',
    jurisdiction: 'International',
    population: 'Everyone',
    accessed: '2026-10-08',
    kind: 'factsheet',
  },
  {
    id: 'reynolds-2016',
    organisation: 'Diabetologia (Reynolds et al.)',
    short: 'Reynolds 2016',
    title: 'Advice to walk after meals is more effective for lowering postprandial glycaemia in type 2 diabetes mellitus than advice that does not specify timing: a randomised crossover study',
    edition: '2016',
    url: 'https://doi.org/10.1007/s00125-016-4085-2',
    locator: 'Abstract: Methods and Results',
    jurisdiction: 'New Zealand',
    population: '41 adults with type 2 diabetes',
    accessed: '2026-10-08',
    kind: 'study',
  },
  {
    id: 'dempsey-2016',
    organisation: 'Diabetes Care (Dempsey et al.)',
    short: 'Dempsey 2016',
    title: 'Benefits for Type 2 Diabetes of Interrupting Prolonged Sitting With Brief Bouts of Light Walking or Simple Resistance Activities',
    edition: '2016',
    url: 'https://doi.org/10.2337/dc15-2336',
    locator: 'Abstract: Research design and methods; Results',
    jurisdiction: 'Australia',
    population: '24 inactive adults with type 2 diabetes and overweight or obesity',
    accessed: '2026-10-08',
    kind: 'study',
  },
  {
    id: 'walkback-2024',
    organisation: 'The Lancet (Pocovi et al., WalkBack trial)',
    short: 'WalkBack 2024',
    title: 'Effectiveness and cost-effectiveness of an individualised, progressive walking and education intervention for the prevention of low back pain recurrence (WalkBack)',
    edition: '2024',
    url: 'https://doi.org/10.1016/S0140-6736(24)00755-4',
    locator: 'Abstract: Methods and Findings',
    jurisdiction: 'Australia',
    population: 'Adults who had recently recovered from an episode of non-specific low back pain',
    accessed: '2026-10-08',
    kind: 'study',
  },
  {
    id: 'ding-2025',
    organisation: 'The Lancet Public Health (Ding et al.)',
    short: 'Ding 2025',
    title: 'Daily steps and health outcomes in adults: a systematic review and dose-response meta-analysis',
    edition: '2025',
    url: 'https://doi.org/10.1016/S2468-2667(25)00164-1',
    locator: 'Abstract: Findings and Interpretation',
    jurisdiction: 'International cohorts',
    population: 'Adults',
    accessed: '2026-10-08',
    kind: 'study',
  },
  {
    id: 'banach-2023',
    organisation: 'European Journal of Preventive Cardiology (Banach et al.)',
    short: 'Banach 2023',
    title: 'The association between daily step count and all-cause and cardiovascular mortality: a meta-analysis',
    edition: '2023',
    url: 'https://doi.org/10.1093/eurjpc/zwad229',
    locator: 'Abstract: Results and Conclusion',
    jurisdiction: 'International cohorts',
    population: 'Adults, generally healthy or at cardiovascular risk',
    accessed: '2026-10-08',
    kind: 'study',
  },
  {
    id: 'koes-2007',
    organisation: 'BMJ (Koes, van Tulder and Peul, clinical review)',
    short: 'Koes 2007',
    title: 'Diagnosis and treatment of sciatica',
    edition: '2007',
    url: 'https://doi.org/10.1136/bmj.39223.428495.BE',
    locator: 'Summary points; What is the value of imaging?; What is the prognosis?; What is the efficacy of conservative treatments for sciatica?',
    jurisdiction: 'International evidence, reviewed in the Netherlands',
    population: 'Adults with sciatica, most often from a disc pressing on a nerve root',
    accessed: '2026-10-08',
    kind: 'study',
  },
];

/**
 * How each source was actually read on the accessed date. Some publishers
 * refuse scripted requests, so the page was read through a public text
 * rendering of the same URL, and journal papers through their PubMed record;
 * `via` says which, so an audit can repeat the check.
 */
export const READ_AT: Record<string, { url: string; via?: string }> = {
  'nin-dgi-2024': { url: 'https://www.nin.res.in/dietaryguidelines/pdfjs/locale/DGI_2024.pdf', via: 'Full PDF downloaded and read as text; page numbers are the printed ones' },
  'ada-soc-2026-s5': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690188/', via: 'PubMed Central full text' },
  'ada-soc-2026-s3': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690170/', via: 'PubMed Central full text' },
  'ada-soc-2026-s10': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690187/', via: 'PubMed Central full text' },
  'ada-diabetes-plate': { url: 'https://diabetesfoodhub.org/blog/what-diabetes-plate' },
  'who-sodium-2026': { url: 'https://www.who.int/news-room/fact-sheets/detail/sodium-reduction' },
  'who-lsss-2025': { url: 'https://iris.who.int/server/api/core/bitstreams/31fad89a-d7c2-450c-9b74-cd2a8752e60f/content', via: 'Guideline PDF from WHO IRIS, linked from the publication page' },
  'who-pa-2020': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7719906/', via: 'PubMed Central full text' },
  'who-alcohol-2023': { url: 'https://www.who.int/europe/news/item/04-01-2023-no-level-of-alcohol-consumption-is-safe-for-our-health' },
  'ods-b12': { url: 'https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'ods-vitamin-d': { url: 'https://ods.od.nih.gov/factsheets/VitaminD-Consumer/', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'ods-vitamin-d-hp': { url: 'https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'nice-ng239': { url: 'https://www.nice.org.uk/guidance/ng239/chapter/recommendations' },
  'endocrine-vitamin-d-2024': { url: 'https://www.endocrine.org/clinical-practice-guidelines/vitamin-d-for-prevention-of-disease' },
  'nice-ng59': { url: 'https://www.nice.org.uk/guidance/ng59/chapter/Recommendations' },
  'nice-ng127': { url: 'https://www.nice.org.uk/guidance/ng127/chapter/recommendations-for-adults-aged-over-16' },
  'acsm-2022': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8802999/', via: 'PubMed Central full text, including Tables 4 and 5 (NCBI E-utilities XML)' },
  'osha-chairs': { url: 'https://www.osha.gov/etools/computer-workstations/components/chairs' },
  'osha-monitors': { url: 'https://www.osha.gov/etools/computer-workstations/components/monitors' },
  'osha-positions': { url: 'https://www.osha.gov/etools/computer-workstations/positions' },
  'osha-work-process': { url: 'https://www.osha.gov/etools/computer-workstations/work-process' },
  'hse-dse-posture': { url: 'https://www.hse.gov.uk/msd/dse/good-posture.htm' },
  'hse-dse-breaks': { url: 'https://www.hse.gov.uk/msd/dse/work-routine.htm' },
  'niddk-ckd-eating': { url: 'https://www.niddk.nih.gov/health-information/kidney-disease/chronic-kidney-disease-ckd/healthy-eating-adults-chronic-kidney-disease' },
  'nhlbi-heart-failure': { url: 'https://www.nhlbi.nih.gov/health/heart-failure/living-with' },
  'nhlbi-sleep-apnea': { url: 'https://www.nhlbi.nih.gov/health/sleep-apnea/symptoms' },
  'cdc-sleep': { url: 'https://www.cdc.gov/sleep/about/index.html', via: 'Read through r.jina.ai text rendering; the site returns 403 to scripts' },
  'niddk-low-glucose': { url: 'https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia' },
  'label-empagliflozin': { url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/204629s063lbl.pdf', via: 'Label PDF from Drugs@FDA, read as text' },
  'label-dapagliflozin': { url: 'https://www.accessdata.fda.gov/drugsatfda_docs/label/2026/202293s035lbl.pdf', via: 'Label PDF from Drugs@FDA, read as text' },
  'cdc-food-safety': { url: 'https://www.cdc.gov/food-safety/foods/weakened-immune-systems.html', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'cdc-water-emergency': { url: 'https://www.cdc.gov/water-emergency/about/index.html', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'nhlbi-dash': { url: 'https://www.nhlbi.nih.gov/education/dash-eating-plan' },
  'nhlbi-heart-attack': { url: 'https://www.nhlbi.nih.gov/health/heart-attack/symptoms' },
  'cdc-stroke': { url: 'https://www.cdc.gov/stroke/signs-symptoms/index.html', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'niams-back-pain': { url: 'https://www.niams.nih.gov/health-topics/back-pain' },
  'cdc-quit-benefits': { url: 'https://www.cdc.gov/tobacco/about/benefits-of-quitting.html', via: 'Read in a headless browser; the site returns 403 to scripts' },
  'who-tobacco': { url: 'https://www.who.int/news-room/fact-sheets/detail/tobacco' },
  'reynolds-2016': { url: 'https://pubmed.ncbi.nlm.nih.gov/27747394/', via: 'PubMed abstract (PMID 27747394)' },
  'dempsey-2016': { url: 'https://pubmed.ncbi.nlm.nih.gov/27208318/', via: 'PubMed abstract (PMID 27208318)' },
  'walkback-2024': { url: 'https://pubmed.ncbi.nlm.nih.gov/38908392/', via: 'PubMed abstract (PMID 38908392)' },
  'ding-2025': { url: 'https://pubmed.ncbi.nlm.nih.gov/40713949/', via: 'PubMed abstract (PMID 40713949)' },
  'banach-2023': { url: 'https://pubmed.ncbi.nlm.nih.gov/37555441/', via: 'PubMed abstract (PMID 37555441)' },
  'rssdi-esi-2020': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7328526/', via: 'PubMed Central full text' },
  'icmr-t2dm-2018': { url: 'https://www.icmr.gov.in/icmrobject/custom_data/pdf/resource-guidelines/ICMR_GuidelinesType2diabetes2018_0.pdf', via: 'Guideline PDF downloaded and read as text; page numbers are the printed ones' },
  'ada-soc-2026-s6': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690178/', via: 'PubMed Central full text' },
  'ada-soc-2026-s7': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC12690173/', via: 'PubMed Central full text' },
  'nice-ng59-context': { url: 'https://www.nice.org.uk/guidance/ng59/chapter/Context' },
  'nice-ng28': { url: 'https://www.nice.org.uk/guidance/ng28/chapter/Blood-glucose-management' },
  'nice-ng136': { url: 'https://www.nice.org.uk/guidance/ng136/chapter/recommendations' },
  'niddk-managing': { url: 'https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes' },
  'cdc-low-sugar': { url: 'https://www.cdc.gov/diabetes/about/low-blood-sugar-hypoglycemia.html', via: 'Read through r.jina.ai text rendering; the site returns 403 to scripts' },
  'aha-home-bp': { url: 'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home', via: 'Read through r.jina.ai text rendering; the site returns 403 to scripts' },
  'aha-bp-911': { url: 'https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/hypertensive-crisis-when-you-should-call-911-for-high-blood-pressure', via: 'Read through r.jina.ai text rendering; the site returns 403 to scripts' },
  'aha-bp-2019': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC11409525/', via: 'PubMed Central author manuscript, Tables 5 and 9' },
  'who-waist-2011': { url: 'https://iris.who.int/server/api/core/bitstreams/ca408ade-05c9-4b7c-8967-6ee5b5e0ccd8/content', via: 'Report PDF from WHO IRIS, linked from the publication page, read as text; page numbers are the printed ones' },
  'koes-2007': { url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC1895638/', via: 'PubMed Central full text' },
};

/**
 * Worth reading, but never the basis of a claim. NHS pages live here and only
 * here (board D32), with a note that they describe UK services.
 */
export const FURTHER_READING: FurtherReading[] = [
  {
    id: 'nin-dgi-booklet',
    organisation: 'ICMR–National Institute of Nutrition',
    title: 'Dietary Guidelines for Indians — short booklet (PDF)',
    url: 'https://www.nin.res.in/downloads/DGI_Booklet_English_CMYK.pdf',
    note: 'The official summary of the 17 guidelines. A large download.',
  },
  {
    id: 'nhs-insomnia',
    organisation: 'NHS (UK)',
    title: 'Insomnia',
    url: 'https://www.nhs.uk/conditions/insomnia/',
    note: 'A UK page. The services and numbers it mentions are for the UK.',
  },
  {
    id: 'nhs-water',
    organisation: 'NHS (UK)',
    title: 'Water, drinks and hydration',
    url: 'https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/',
    note: 'A UK page. It does not cover fluid limits for kidney or heart conditions.',
  },
];
